# autogenerated by docgen
# source: /home/runner/work/Nim/Nim/lib/js/asyncjs.nim
# rdoccmd: -d:nimExperimentalAsyncjsThen
import "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim"
import "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim"
