/* Generated by the Nim Compiler v1.5.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33555128 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555120 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555122 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554456 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555915 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555083 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555165 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554440 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555164 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555112 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555113 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555124 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554439 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NNI33555124 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555124.node = NNI33555124;
var NNI33555113 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555113.node = NNI33555113;
NTI33555164.base = NTI33555112;
NTI33555165.base = NTI33555112;
var NNI33555112 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555164, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554440, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554439, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554439, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555165, name: "up", sons: null}]};
NTI33555112.node = NNI33555112;
var NNI33555083 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555083.node = NNI33555083;
NTI33555112.base = NTI33555083;
NTI33555113.base = NTI33555112;
NTI33555124.base = NTI33555113;
var NNI33555915 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554440, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554456, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554440, name: "Field2", sons: null}]};
NTI33555915.node = NNI33555915;
var NNI33555122 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555122.node = NNI33555122;
var NNI33555120 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555120.node = NNI33555120;
NTI33555120.base = NTI33555113;
NTI33555122.base = NTI33555120;
var NNI33555128 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555128.node = NNI33555128;
NTI33555128.base = NTI33555113;

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557136, src_33557137, ti_33557138) {
  var result_33557147 = null;

    switch (ti_33557138.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557127(ti_33557138))) {
      result_33557147 = src_33557137;
      }
      else {
        result_33557147 = [src_33557137[0], src_33557137[1]];
      }
      
      break;
    case 19:
            if (dest_33557136 === null || dest_33557136 === undefined) {
        dest_33557136 = {};
      }
      else {
        for (var key in dest_33557136) { delete dest_33557136[key]; }
      }
      for (var key in src_33557137) { dest_33557136[key] = src_33557137[key]; }
      result_33557147 = dest_33557136;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557138.base == null))) {
      result_33557147 = nimCopy(dest_33557136, src_33557137, ti_33557138.base);
      }
      else {
      if ((ti_33557138.kind == 17)) {
      result_33557147 = (dest_33557136 === null || dest_33557136 === undefined) ? {m_type: ti_33557138} : dest_33557136;
      }
      else {
        result_33557147 = (dest_33557136 === null || dest_33557136 === undefined) ? {} : dest_33557136;
      }
      }
      nimCopyAux(result_33557147, src_33557137, ti_33557138.node);
      break;
    case 24:
    case 4:
    case 27:
    case 16:
            if (src_33557137 === null) {
        result_33557147 = null;
      }
      else {
        if (dest_33557136 === null || dest_33557136 === undefined) {
          dest_33557136 = new Array(src_33557137.length);
        }
        else {
          dest_33557136.length = src_33557137.length;
        }
        result_33557147 = dest_33557136;
        for (var i = 0; i < src_33557137.length; ++i) {
          result_33557147[i] = nimCopy(result_33557147[i], src_33557137[i], ti_33557138.base);
        }
      }
    
      break;
    case 28:
            if (src_33557137 !== null) {
        result_33557147 = src_33557137.slice(0);
      }
    
      break;
    default: 
      result_33557147 = src_33557137;
      break;
    }

  return result_33557147;

}

function makeNimstrLit(c_33556797) {
      var result = [];
  for (var i = 0; i < c_33556797.length; ++i) {
    result[i] = c_33556797.charCodeAt(i);
  }
  return result;
  

  
}

function arrayConstr(len_33557175, value_33557176, typ_33557177) {
        var result = new Array(len_33557175);
    for (var i = 0; i < len_33557175; ++i) result[i] = nimCopy(null, value_33557176, typ_33557177);
    return result;
  

  
}

function cstrToNimstr(c_33556800) {
      var ln = c_33556800.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556800.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556800.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_33556803) {
                    var Temporary5;
            var Temporary7;

  var result_33556804 = null;

    var res_33556838 = newSeq_33556821((s_33556803).length);
    var i_33556839 = 0;
    var j_33556840 = 0;
    Label1: do {
        Label2: while (true) {
        if (!(i_33556839 < (s_33556803).length)) break Label2;
          var c_33556841 = s_33556803[i_33556839];
          if ((c_33556841 < 128)) {
          res_33556838[j_33556840] = String.fromCharCode(c_33556841);
          i_33556839 += 1;
          }
          else {
            var helper_33556853 = newSeq_33556821(0);
            Label3: do {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556854 = c_33556841.toString(16);
                  if ((((code_33556854) == null ? 0 : (code_33556854).length) == 1)) {
                  helper_33556853.push("%0");;
                  }
                  else {
                  helper_33556853.push("%");;
                  }
                  
                  helper_33556853.push(code_33556854);;
                  i_33556839 += 1;
                    if (((s_33556803).length <= i_33556839)) Temporary5 = true; else {                      Temporary5 = (s_33556803[i_33556839] < 128);                    }                  if (Temporary5) {
                  break Label3;
                  }
                  
                  c_33556841 = s_33556803[i_33556839];
                }
            } while (false);
++excHandler;
            Temporary7 = framePtr;
            try {
            res_33556838[j_33556840] = decodeURIComponent(helper_33556853.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            framePtr = Temporary7;
            res_33556838[j_33556840] = helper_33556853.join("");
            lastJSError = prevJSError;
            } finally {
            framePtr = Temporary7;
            }
          }
          
          j_33556840 += 1;
        }
    } while (false);
    if (res_33556838.length < j_33556840) { for (var i = res_33556838.length ; i < j_33556840 ; ++i) res_33556838.push(null); }
               else { res_33556838.length = j_33556840; };
    result_33556804 = res_33556838.join("");

  return result_33556804;

}

function raiseException(e_33556664, ename_33556665) {
    e_33556664.name = ename_33556665;
    if ((excHandler == 0)) {
    unhandledException(e_33556664);
    }
    
    e_33556664.trace = nimCopy(null, rawWriteStackTrace_33556628(), NTI33554439);
    throw e_33556664;

  
}

function eqStrings(a_33556927, b_33556928) {
        if (a_33556927 == b_33556928) return true;
    if (a_33556927 === null && b_33556928.length == 0) return true;
    if (b_33556928 === null && a_33556927.length == 0) return true;
    if ((!a_33556927) || (!b_33556928)) return false;
    var alen = a_33556927.length;
    if (alen != b_33556928.length) return false;
    for (var i = 0; i < alen; ++i)
      if (a_33556927[i] != b_33556928[i]) return false;
    return true;
  

  
}

function subInt(a_33556940, b_33556941) {
        var result = a_33556940 - b_33556941;
    checkOverflowInt(result);
    return result;
  

  
}

function chckIndx(i_33557180, a_33557181, b_33557182) {
      var Temporary1;

  var result_33557183 = 0;

  BeforeRet: do {
      if (!(a_33557181 <= i_33557180)) Temporary1 = false; else {        Temporary1 = (i_33557180 <= b_33557182);      }    if (Temporary1) {
    result_33557183 = i_33557180;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557180, a_33557181, b_33557182);
    }
    
  } while (false);

  return result_33557183;

}

function addInt(a_33556936, b_33556937) {
        var result = a_33556936 + b_33556937;
    checkOverflowInt(result);
    return result;
  

  
}
if (!Math.trunc) {
  Math.trunc = function(v) {
    v = +v;
    if (!isFinite(v)) return v;
    return (v - v % 1) || (v < 0 ? -0 : v === 0 ? v : 0);
  };
}

var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function isFatPointer_33557127(ti_33557128) {
  var result_33557129 = false;

  BeforeRet: do {
    result_33557129 = !((ConstSet1[ti_33557128.base.kind] != undefined));
    break BeforeRet;
  } while (false);

  return result_33557129;

}

function nimCopyAux(dest_33557140, src_33557141, n_33557142) {
    switch (n_33557142.kind) {
    case 0:
      break;
    case 1:
            dest_33557140[n_33557142.offset] = nimCopy(dest_33557140[n_33557142.offset], src_33557141[n_33557142.offset], n_33557142.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557142.sons.length; i++) {
      nimCopyAux(dest_33557140, src_33557141, n_33557142.sons[i]);
    }
    
      break;
    case 3:
            dest_33557140[n_33557142.offset] = nimCopy(dest_33557140[n_33557142.offset], src_33557141[n_33557142.offset], n_33557142.typ);
      for (var i = 0; i < n_33557142.sons.length; ++i) {
        nimCopyAux(dest_33557140, src_33557141, n_33557142.sons[i][1]);
      }
    
      break;
    }

  
}

function add_33556420(x_33556421, x_33556421_Idx, y_33556422) {
          if (x_33556421[x_33556421_Idx] === null) { x_33556421[x_33556421_Idx] = []; }
      var off = x_33556421[x_33556421_Idx].length;
      x_33556421[x_33556421_Idx].length += y_33556422.length;
      for (var i = 0; i < y_33556422.length; ++i) {
        x_33556421[x_33556421_Idx][off+i] = y_33556422.charCodeAt(i);
      }
    

  
}

function auxWriteStackTrace_33556556(f_33556557) {
          var Temporary3;

  var result_33556558 = [[]];

    var it_33556566 = f_33556557;
    var i_33556567 = 0;
    var total_33556568 = 0;
    var tempFrames_33556569 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555915);
    Label1: do {
        Label2: while (true) {
          if (!!((it_33556566 == null))) Temporary3 = false; else {            Temporary3 = (i_33556567 <= 63);          }        if (!Temporary3) break Label2;
          tempFrames_33556569[i_33556567].Field0 = it_33556566.procname;
          tempFrames_33556569[i_33556567].Field1 = it_33556566.line;
          tempFrames_33556569[i_33556567].Field2 = it_33556566.filename;
          i_33556567 += 1;
          total_33556568 += 1;
          it_33556566 = it_33556566.prev;
        }
    } while (false);
    Label4: do {
        Label5: while (true) {
        if (!!((it_33556566 == null))) break Label5;
          total_33556568 += 1;
          it_33556566 = it_33556566.prev;
        }
    } while (false);
    result_33556558[0] = nimCopy(null, [], NTI33554439);
    if (!((total_33556568 == i_33556567))) {
    result_33556558[0].push.apply(result_33556558[0], makeNimstrLit("("));;
    result_33556558[0].push.apply(result_33556558[0], cstrToNimstr(((total_33556568 - i_33556567)) + ""));;
    result_33556558[0].push.apply(result_33556558[0], makeNimstrLit(" calls omitted) ...\x0A"));;
    }
    
    Label6: do {
      var j_33556599 = 0;
      var colontmp__553648182 = 0;
      colontmp__553648182 = (i_33556567 - 1);
      var res_553648184 = colontmp__553648182;
      Label7: do {
          Label8: while (true) {
          if (!(0 <= res_553648184)) break Label8;
            j_33556599 = res_553648184;
            result_33556558[0].push.apply(result_33556558[0], cstrToNimstr(tempFrames_33556569[j_33556599].Field2));;
            if ((0 < tempFrames_33556569[j_33556599].Field1)) {
            result_33556558[0].push.apply(result_33556558[0], makeNimstrLit("("));;
            result_33556558[0].push.apply(result_33556558[0], cstrToNimstr((tempFrames_33556569[j_33556599].Field1) + ""));;
            if (false) {
            result_33556558[0].push.apply(result_33556558[0], makeNimstrLit(", "));;
            result_33556558[0].push.apply(result_33556558[0], makeNimstrLit("0"));;
            }
            
            result_33556558[0].push.apply(result_33556558[0], makeNimstrLit(")"));;
            }
            
            result_33556558[0].push.apply(result_33556558[0], makeNimstrLit(" at "));;
            add_33556420(result_33556558, 0, tempFrames_33556569[j_33556599].Field0);
            result_33556558[0].push.apply(result_33556558[0], makeNimstrLit("\x0A"));;
            res_553648184 -= 1;
          }
      } while (false);
    } while (false);

  return result_33556558[0];

}

function rawWriteStackTrace_33556628() {
  var result_33556629 = [];

    if (!((framePtr == null))) {
    result_33556629 = nimCopy(null, (makeNimstrLit("Traceback (most recent call last)\x0A") || []).concat(auxWriteStackTrace_33556556(framePtr) || []), NTI33554439);
    }
    else {
      result_33556629 = nimCopy(null, makeNimstrLit("No stack traceback available\x0A"), NTI33554439);
    }
    

  return result_33556629;

}

function newSeq_33556821(len_33556823) {
  var result_33556824 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 680;
    result_33556824 = new Array(len_33556823); for (var i = 0 ; i < len_33556823 ; ++i) { result_33556824[i] = null; }  framePtr = F.prev;

  return result_33556824;

}

function unhandledException(e_33556660) {
    var buf_33556661 = [[]];
    if (!(((e_33556660.message).length == 0))) {
    buf_33556661[0].push.apply(buf_33556661[0], makeNimstrLit("Error: unhandled exception: "));;
    buf_33556661[0].push.apply(buf_33556661[0], e_33556660.message);;
    }
    else {
    buf_33556661[0].push.apply(buf_33556661[0], makeNimstrLit("Error: unhandled exception"));;
    }
    
    buf_33556661[0].push.apply(buf_33556661[0], makeNimstrLit(" ["));;
    add_33556420(buf_33556661, 0, e_33556660.name);
    buf_33556661[0].push.apply(buf_33556661[0], makeNimstrLit("]\x0A"));;
    buf_33556661[0].push.apply(buf_33556661[0], rawWriteStackTrace_33556628());;
    var cbuf_33556662 = toJSStr(buf_33556661[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556662);
  }
  else {
    throw cbuf_33556662;
  }
  

  
}

function sysFatal_218103844(message_218103847) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    raiseException({message: nimCopy(null, message_218103847, NTI33554439), m_type: NTI33555124, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert_218103842(msg_218103843) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/assertions.nim", line: 0};
  framePtr = F;
    F.line = 29;
    sysFatal_218103844(msg_218103843);
  framePtr = F.prev;

  
}

function failedAssertImpl_218103866(msg_218103867) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/assertions.nim", line: 0};
  framePtr = F;
    F.line = 39;
    raiseAssert_218103842(msg_218103867);
  framePtr = F.prev;

  
}
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
if (!((BigInt(1234567890) == BigInt("1234567890")))) {
F.line = 11;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim(8, 12) `big(1234567890) == big\"1234567890\"` "));
}

if (!(((BigInt(999) == BigInt(999)) && (BigInt(999) == BigInt(999))))) {
F.line = 11;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim(9, 12) `0b00000000000000000000001111100111.big == 0o000000001747.big and\x0A    0o000000001747.big == 999.big` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
if (!((BigInt("-1") == (BigInt("1") - BigInt("2"))))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(8, 12) `-1\'big == 1\'big - 2\'big` "));
}

if (!((BigInt("-12") == BigInt("-12")))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(10, 12) `-12\'big == big\"-12\"` "));
}

if (!((BigInt("12") == BigInt(12)))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(11, 12) `12\'big == 12.big` "));
}

if (!((BigInt("0b101") == BigInt(5)))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(12, 12) `0b101\'big == 0b00000000000000000000000000000101.big` "));
}

if (!((BigInt("0o701") == BigInt(449)))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(13, 12) `0o701\'big == 0o000000000701.big` "));
}

if (!((BigInt("0xdeadbeaf") == BigInt(3735928495)))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(14, 12) `0xdeadbeaf\'big == 0x00000000DEADBEAF\'i64.big` "));
}

if (!((BigInt("0xffffffffffffffff") == ((BigInt("1") << BigInt("64")) - BigInt("1"))))) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(15, 12) `0xffffffffffffffff\'big == (1\'big shl 64\'big) - 1\'big` "));
}

if (false) {
F.line = 18;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim(16, 3) `not compiles(static(12\'big))` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
if (!((BigInt("2147483647").toString(2) == "1111111111111111111111111111111"))) {
F.line = 38;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim(8, 12) `big\"2147483647\".toCstring(2) == \"1111111111111111111111111111111\".cstring` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function HEX24_570425373(this_570425374) {
  var result_570425375 = [];

  var F = {procname: "jsbigints.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
  framePtr = F;
    F.line = 46;
    result_570425375 = nimCopy(null, (cstrToNimstr(this_570425374.toString()) || []).concat([110]), NTI33554439);
  framePtr = F.prev;

  return result_570425375;

}
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
if (!(eqStrings(HEX24_570425373(BigInt("1024")), makeNimstrLit("1024n")))) {
F.line = 47;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim(8, 12) `$big\"1024\" == \"1024n\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_4", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_4.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
if (!(((() => { const i = (BigInt("3") + ((BigInt("2")) ** BigInt("66"))), b = 13; return BigInt.asIntN(b, i) })() == BigInt("3")))) {
F.line = 54;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim(8, 12) `(big(\"3\") + big(\"2\") ** big(\"66\")).wrapToInt(13) == big(\"3\")` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_5", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_5.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
if (!(((() => { const i = (BigInt("3") + ((BigInt("2")) ** BigInt("66"))), b = 66; return BigInt.asUintN(b, i) })() == BigInt("3")))) {
F.line = 61;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim(8, 12) `(big(\"3\") + big(\"2\") ** big(\"66\")).wrapToUint(66) == big(\"3\")` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_6", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_6.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
if (!((Number(BigInt("2147483647")) == 2147483647))) {
F.line = 66;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim(8, 12) `toNumber(big\"2147483647\") == 2147483647.BiggestInt` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_7", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_7.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
if (!(((BigInt("9") + BigInt("1")) == BigInt("10")))) {
F.line = 70;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim(8, 12) `(big\"9\" + big\"1\") == big\"10\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_8", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_8.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
if (!(((BigInt("9") - BigInt("1")) == BigInt("8")))) {
F.line = 74;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim(8, 12) `(big\"9\" - big\"1\") == big\"8\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_9", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_9.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
if (!(((BigInt("42") * BigInt("9")) == BigInt("378")))) {
F.line = 78;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim(8, 12) `(big\"42\" * big\"9\") == big\"378\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_10", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_10.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
if (!(((BigInt("13") / BigInt("3")) == BigInt("4")))) {
F.line = 83;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(8, 12) `big\"13\" div big\"3\" == big\"4\"` "));
}

if (!(((BigInt("-13") / BigInt("3")) == BigInt("-4")))) {
F.line = 83;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(9, 12) `big\"-13\" div big\"3\" == big\"-4\"` "));
}

if (!(((BigInt("13") / BigInt("-3")) == BigInt("-4")))) {
F.line = 83;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(10, 12) `big\"13\" div big\"-3\" == big\"-4\"` "));
}

if (!(((BigInt("-13") / BigInt("-3")) == BigInt("4")))) {
F.line = 83;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim(11, 12) `big\"-13\" div big\"-3\" == big\"4\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_11", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_11.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
if (!(((BigInt("13") % BigInt("3")) == BigInt("1")))) {
F.line = 91;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(8, 12) `big\"13\" mod big\"3\" == big\"1\"` "));
}

if (!(((BigInt("-13") % BigInt("3")) == BigInt("-1")))) {
F.line = 91;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(9, 12) `big\"-13\" mod big\"3\" == big\"-1\"` "));
}

if (!(((BigInt("13") % BigInt("-3")) == BigInt("1")))) {
F.line = 91;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(10, 12) `big\"13\" mod big\"-3\" == big\"1\"` "));
}

if (!(((BigInt("-13") % BigInt("-3")) == BigInt("-1")))) {
F.line = 91;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim(11, 12) `big\"-13\" mod big\"-3\" == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_12", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_12.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
if (!((BigInt("2") < BigInt("9")))) {
F.line = 98;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim(8, 12) `big\"2\" < big\"9\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_13", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_13.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
if (!((BigInt("1") <= BigInt("5")))) {
F.line = 102;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim(8, 12) `big\"1\" <= big\"5\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_14", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_14.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
if (!((BigInt("42") == BigInt("42")))) {
F.line = 106;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim(8, 12) `big\"42\" == big\"42\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_15", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_15.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
if (!((((BigInt("2")) ** BigInt("64")) == BigInt("18446744073709551616")))) {
F.line = 111;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(8, 12) `big\"2\" ** big\"64\" == big\"18446744073709551616\"` "));
}

if (!((((BigInt("-2")) ** BigInt("3")) == BigInt("-8")))) {
F.line = 111;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(9, 12) `big\"-2\" ** big\"3\" == big\"-8\"` "));
}

if (!(((((-BigInt("2"))) ** BigInt("2")) == BigInt("4")))) {
F.line = 111;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(10, 12) `-big\"2\" ** big\"2\" == big\"4\"` "));
}

if (!((((BigInt("0")) ** BigInt("0")) == BigInt("1")))) {
F.line = 111;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(11, 12) `big\"0\" ** big\"0\" == big\"1\"` "));
}

F.line = 111;
var ok_822083606 = [false];
F.line = 111;
++excHandler;
try {
F.line = 111;
var _ = ((BigInt("2")) ** BigInt("-1"));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
framePtr = F;
F.line = 111;
ok_822083606[0] = true;
lastJSError = prevJSError;
} finally {
framePtr = F;
}
if (!(ok_822083606[0])) {
F.line = 111;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim(15, 12) `ok` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_16", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_16.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") & BigInt("2")) == BigInt("2")))) {
F.line = 124;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim(8, 12) `(big\"555\" and big\"2\") == big\"2\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_17", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_17.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") | BigInt("2")) == BigInt("555")))) {
F.line = 128;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim(8, 12) `(big\"555\" or big\"2\") == big\"555\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_18", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_18.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
if (!(((BigInt("555") ^ BigInt("2")) == BigInt("553")))) {
F.line = 132;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim(8, 12) `(big\"555\" xor big\"2\") == big\"553\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_19", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_19.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
if (!(((BigInt("999") << BigInt("2")) == BigInt("3996")))) {
F.line = 136;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim(8, 12) `(big\"999\" shl big\"2\") == big\"3996\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_20", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_20.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
if (!(((BigInt("999") >> BigInt("2")) == BigInt("249")))) {
F.line = 140;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim(8, 12) `(big\"999\" shr big\"2\") == big\"249\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_21", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_21.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
if (!(((-BigInt("10101010101")) == BigInt("-10101010101")))) {
F.line = 144;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim(8, 12) `-(big\"10101010101\") == big\"-10101010101\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_22", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_22.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
F.line = 148;
var big1_939524098 = [BigInt("1")];
F.line = 148;
(++[big1_939524098, 0][0][0]);
if (!((big1_939524098[0] == BigInt("2")))) {
F.line = 148;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim(10, 12) `big1 == big\"2\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_23", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_23.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
F.line = 154;
var big1_956301314 = [BigInt("2")];
F.line = 154;
(--[big1_956301314, 0][0][0]);
if (!((big1_956301314[0] == BigInt("1")))) {
F.line = 154;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim(10, 12) `big1 == big\"1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_24", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_24.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
F.line = 160;
var big1_973078530 = [BigInt("1")];
F.line = 160;
([big1_973078530, 0][0][0] += BigInt("2"));
if (!((big1_973078530[0] == BigInt("3")))) {
F.line = 160;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim(10, 12) `big1 == big\"3\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_25", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_25.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
F.line = 166;
var big1_989855746 = [BigInt("1")];
F.line = 166;
([big1_989855746, 0][0][0] -= BigInt("2"));
if (!((big1_989855746[0] == BigInt("-1")))) {
F.line = 166;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim(10, 12) `big1 == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_26", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_26.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
F.line = 172;
var big1_1006632962 = [BigInt("1")];
F.line = 172;
([big1_1006632962, 0][0][0] += BigInt("2"));
if (!((big1_1006632962[0] == BigInt("3")))) {
F.line = 172;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim(10, 12) `big1 == big\"3\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_27", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_27.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
F.line = 178;
var big1_1023410178 = [BigInt("1")];
F.line = 178;
([big1_1023410178, 0][0][0] -= BigInt("2"));
if (!((big1_1023410178[0] == BigInt("-1")))) {
F.line = 178;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim(10, 12) `big1 == big\"-1\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_28", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_28.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
F.line = 184;
var big1_1040187394 = [BigInt("2")];
F.line = 184;
([big1_1040187394, 0][0][0] *= BigInt("4"));
if (!((big1_1040187394[0] == BigInt("8")))) {
F.line = 184;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim(10, 12) `big1 == big\"8\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_29", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_29.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
F.line = 191;
var big1_1056964610 = [BigInt("11")];
F.line = 191;
([big1_1056964610, 0][0][0] /= BigInt("2"));
if (!((big1_1056964610[0] == BigInt("5")))) {
F.line = 191;
failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim(10, 12) `big1 == big\"5\"` "));
}

framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_30", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_30.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function raiseOverflow() {
    raiseException({message: makeNimstrLit("over- or underflow"), parent: null, m_type: NTI33555122, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33556934) {
        if (a_33556934 > 2147483647 || a_33556934 < -2147483648) raiseOverflow();
  

  
}

function raiseIndexError(i_33556751, a_33556752, b_33556753) {
    var Temporary1;

    if ((b_33556753 < a_33556752)) {
    Temporary1 = makeNimstrLit("index out of bounds, the container is empty");
    }
    else {
    Temporary1 = (makeNimstrLit("index ") || []).concat(cstrToNimstr((i_33556751) + "") || [],makeNimstrLit(" not in ") || [],cstrToNimstr((a_33556752) + "") || [],makeNimstrLit(" .. ") || [],cstrToNimstr((b_33556753) + "") || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554439), parent: null, m_type: NTI33555128, name: null, trace: [], up: null}, "IndexDefect");

  
}

function HEX3DHEX3D_1073741883(x_1073741885, y_1073741886) {
  var result_1073741887 = false;

  var F = {procname: "==.==", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/comparisons.nim", line: 0};
  framePtr = F;
  BeforeRet: do {
    F.line = 301;
    var sameObject_1073741895 = false;
    F.line = 302;
    sameObject_1073741895 = x_1073741885 === y_1073741886
    if (sameObject_1073741895) {
    F.line = 303;
    result_1073741887 = true;
    break BeforeRet;
    }
    
    if (!(((x_1073741885).length == (y_1073741886).length))) {
    F.line = 306;
    result_1073741887 = false;
    break BeforeRet;
    }
    
    Label1: do {
      F.line = 308;
      var i_1073741909 = 0;
      F.line = 75;
      var colontmp__1073741983 = 0;
      F.line = 308;
      colontmp__1073741983 = subInt((x_1073741885).length, 1);
      F.line = 90;
      var res_1073741985 = 0;
      Label2: do {
        F.line = 91;
          Label3: while (true) {
          if (!(res_1073741985 <= colontmp__1073741983)) break Label3;
            F.line = 308;
            i_1073741909 = res_1073741985;
            if (!((x_1073741885[chckIndx(i_1073741909, 0, (x_1073741885).length - 1)] == y_1073741886[chckIndx(i_1073741909, 0, (y_1073741886).length - 1)]))) {
            F.line = 310;
            result_1073741887 = false;
            break BeforeRet;
            }
            
            F.line = 93;
            res_1073741985 = addInt(res_1073741985, 1);
          }
      } while (false);
    } while (false);
    F.line = 312;
    result_1073741887 = true;
    break BeforeRet;
  } while (false);
  framePtr = F.prev;

  return result_1073741887;

}

function HEX5BHEX5D_1073741915(s_1073741917, i_1073741918) {
  var result_1073741919 = null;
  var result_1073741919_Idx = 0;

  var F = {procname: "[].[]", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 2644;
    result_1073741919 = s_1073741917; result_1073741919_Idx = chckIndx(subInt((s_1073741917).length, i_1073741918), 0, (s_1073741917).length - 1);
  framePtr = F.prev;

  return [result_1073741919, result_1073741919_Idx];

}
    var Temporary4;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
Label2: do {
  F.line = 207;
  var big1_1073741826 = BigInt("2147483647");
  F.line = 207;
  var big2_1073741827 = BigInt("666");
  if (false) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(11, 14) `JsBigInt isnot int` "));
  }
  
  if (!(!((big1_1073741826 == big2_1073741827)))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(12, 14) `big1 != big2` "));
  }
  
  if (!((big2_1073741827 < big1_1073741826))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(13, 14) `big1 > big2` "));
  }
  
  if (!((big2_1073741827 <= big1_1073741826))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(14, 14) `big1 >= big2` "));
  }
  
  if (!((big2_1073741827 < big1_1073741826))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(15, 14) `big2 < big1` "));
  }
  
  if (!((big2_1073741827 <= big1_1073741826))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(16, 14) `big2 <= big1` "));
  }
  
  if (!(!((big1_1073741826 == big2_1073741827)))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(17, 5) `not (big1 == big2)` "));
  }
  
  F.line = 207;
  var z_1073741868 = 0n;
  if (!(eqStrings(HEX24_570425373(z_1073741868), makeNimstrLit("0n")))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(19, 14) `$z == \"0n\"` "));
  }
  
} while (false);
Label3: do {
  F.line = 207;
  var a_1073741874 = [[]];
  F.line = 207;
  if (a_1073741874[0].length < 2) { for (var i = a_1073741874[0].length ; i < 2 ; ++i) a_1073741874[0].push(0n); }
               else { a_1073741874[0].length = 2; };
  if (!(HEX3DHEX3D_1073741883(a_1073741874[0], [BigInt("0"), BigInt("0")]))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(23, 14) `a == @[big\"0\", big\"0\"]` "));
  }
  
  if (!(((Temporary4 = HEX5BHEX5D_1073741915(a_1073741874[0], 1), Temporary4)[0][Temporary4[1]] == BigInt("0")))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(24, 14) `a[^1] == big\"0\"` "));
  }
  
  F.line = 207;
  var b_1073741938 = [0n];
  if (!((b_1073741938[0] == BigInt("0")))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(26, 14) `b == big\"0\"` "));
  }
  
  if (!((b_1073741938[0] == 0n))) {
  F.line = 207;
  failedAssertImpl_218103866(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim(27, 14) `b == JsBigInt.default` "));
  }
  
} while (false);
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_examples_31", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_examples_31.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsbigints_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
