#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/std/jsbigints.nim(137, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", 137, 3).}:
  doAssert (big"999" shl big"2") == big"3996"

