#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/std/jsbigints.nim(86, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", 86, 3).}:
  doAssert big"13" div big"3" == big"4"
  doAssert big"-13" div big"3" == big"-4"
  doAssert big"13" div big"-3" == big"-4"
  doAssert big"-13" div big"-3" == big"4"

