#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/std/jsbigints.nim(66, 3)
rdoccmd: 
]#
import "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", 66, 3).}:
  doAssert toNumber(big"2147483647") == 2147483647.BiggestInt

