#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/js/jscore.nim(153, 21)
rdoccmd: -r:off
]#
import std/assertions
import "/home/runner/work/Nim/Nim/lib/js/jscore.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/js/jscore.nim", 153, 21).}:
  queueMicrotask(proc() = echo "Microtask")

