/* Generated by the Nim Compiler v2.3.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555871 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555179 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555178 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555176 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI33555176 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555176.node = NNI33555176;
NTI33555178.base = NTI33555175;
NTI33555179.base = NTI33555175;
var NNI33555175 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555178, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555179, name: "up", sons: null}]};
NTI33555175.node = NNI33555175;
var NNI33555171 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555171.node = NNI33555171;
NTI33555175.base = NTI33555171;
NTI33555176.base = NTI33555175;
var NNI33555871 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555871.node = NNI33555871;

function isObj(obj_p0, subclass_p1) {
  var result_33557435 = false;

  BeforeRet: {
    var x_33557436 = obj_p0;
    if ((x_33557436 == subclass_p1)) {
    result_33557435 = true;
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!!((x_33557436 == subclass_p1))) break Label2;
          if ((x_33557436 == null)) {
          result_33557435 = false;
          break BeforeRet;
          }
          
          x_33557436 = x_33557436.base;
        }
    };
    result_33557435 = true;
    break BeforeRet;
  };

  return result_33557435;

}

function nimAddStrStr(x_p0, y_p1) {
      var L = y_p1.length;
  for (var i = 0; i < L; ++i) {
    x_p0.push(y_p1[i]);
  }
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557334 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_u0__system(ti_p2))) {
      result_33557334 = src_p1;
      }
      else {
        result_33557334 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557334 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557334 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557334 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557334 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557334, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557334 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557334 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557334 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557334[i] = nimCopy(result_33557334[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557334 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557334 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557334[i] = nimCopy(result_33557334[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557334 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557334 = src_p1;
      break;
    }

  return result_33557334;

}

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_p0) {
  var result_33556923 = null;

    var res_33556989 = newSeq_u9__system((s_p0).length);
    var i_33556990 = 0;
    var j_33556991 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556990 < (s_p0).length)) break Label2;
          var c_33556992 = s_p0[i_33556990];
          if ((c_33556992 < 128)) {
          res_33556989[j_33556991] = String.fromCharCode(c_33556992);
          i_33556990 += 1;
          }
          else {
            var helper_33557014 = newSeq_u9__system(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33557015 = c_33556992.toString(16);
                  if ((((code_33557015) == null ? 0 : (code_33557015).length) == 1)) {
                  helper_33557014.push("%0");;
                  }
                  else {
                  helper_33557014.push("%");;
                  }
                  
                  helper_33557014.push(code_33557015);;
                  i_33556990 += 1;
                  if ((((s_p0).length <= i_33556990) || (s_p0[i_33556990] < 128))) {
                  break Label3;
                  }
                  
                  c_33556992 = s_p0[i_33556990];
                }
            };
++excHandler;
            try {
            res_33556989[j_33556991] = decodeURIComponent(helper_33557014.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            raiseDefect();
            res_33556989[j_33556991] = helper_33557014.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556991 += 1;
        }
    };
    if (res_33556989.length < j_33556991) { for (var i = res_33556989.length ; i < j_33556991 ; ++i) res_33556989.push(null); }
               else { res_33556989.length = j_33556991; };
    result_33556923 = res_33556989.join("");

  return result_33556923;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_u9__system(len_p0) {
  var result_33556968 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 658;
    F.filename = "system.nim";
    result_33556968 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556968[i] = null; }  framePtr = F.prev;

  return result_33556968;

}

function isNimException_u0__system() {
    return lastJSError && lastJSError.m_type;

  
}

function getCurrentException() {
  var result_33556467 = null;

    if (isNimException_u0__system()) {
    result_33556467 = lastJSError;
    }
    

  return result_33556467;

}

function add_u4__system(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function isFatPointer_u0__system(ti_p0) {
  var result_33557316 = false;

  BeforeRet: {
    result_33557316 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557316;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function addChars_u4__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_335544521 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = (old_335544521 + n_p3), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_335544527 = 0;
      var i_687865877 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_687865877 < n_p3)) break Label4;
            iHEX60gensym4_335544527 = i_687865877;
            result_p0[result_p0_Idx][(old_335544521 + iHEX60gensym4_335544527)] = x_p1.charCodeAt((start_p2 + iHEX60gensym4_335544527));
            i_687865877 += 1;
          }
      };
    };

  
}

function addChars_u3__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1) {
    addChars_u4__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt_u1__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1) {
    addChars_u3__stdZprivateZdigitsutils(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt_u2__stdZprivateZdigitsutils(result_p0, result_p0_Idx, x_p1) {
    addInt_u1__stdZprivateZdigitsutils(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24_u1__systemZdollars(xHEX60gensym0_p0) {
  var result_385875984 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 20;
    F.filename = "dollars.nim";
    result_385875984[0] = nimCopy(null, [], NTI33554449);
    F.line = 21;
    addInt_u2__stdZprivateZdigitsutils(result_385875984, 0, xHEX60gensym0_p0);
  framePtr = F.prev;

  return result_385875984[0];

}

function auxWriteStackTrace_u0__system(f_p0) {
  var result_33556535 = [[]];

    var it_33556540 = f_p0;
    var i_33556541 = 0;
    var total_33556542 = 0;
    var tempFrames_33556543 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555871);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556540 == null)) && (i_33556541 <= 63))) break Label2;
          tempFrames_33556543[i_33556541].Field0 = it_33556540.procname;
          tempFrames_33556543[i_33556541].Field1 = it_33556540.line;
          tempFrames_33556543[i_33556541].Field2 = it_33556540.filename;
          i_33556541 += 1;
          total_33556542 += 1;
          it_33556540 = it_33556540.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556540 == null))) break Label4;
          total_33556542 += 1;
          it_33556540 = it_33556540.prev;
        }
    };
    result_33556535[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556542 == i_33556541))) {
    nimAddStrStr(result_33556535[0], [40]);;
    nimAddStrStr(result_33556535[0], HEX24_u1__systemZdollars((total_33556542 - i_33556541)));;
    nimAddStrStr(result_33556535[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556572 = 0;
      var colontmp__687865869 = 0;
      colontmp__687865869 = (i_33556541 - 1);
      var res_687865871 = colontmp__687865869;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_687865871)) break Label7;
            j_33556572 = res_687865871;
            nimAddStrStr(result_33556535[0], cstrToNimstr(tempFrames_33556543[j_33556572].Field2));;
            if ((0 < tempFrames_33556543[j_33556572].Field1)) {
            nimAddStrStr(result_33556535[0], [40]);;
            addInt_u2__stdZprivateZdigitsutils(result_33556535, 0, tempFrames_33556543[j_33556572].Field1);
            if (false) {
            nimAddStrStr(result_33556535[0], [44,32]);;
            addInt_u2__stdZprivateZdigitsutils(result_33556535, 0, 0);
            }
            
            nimAddStrStr(result_33556535[0], [41]);;
            }
            
            nimAddStrStr(result_33556535[0], [32,97,116,32]);;
            add_u4__system(result_33556535, 0, tempFrames_33556543[j_33556572].Field0);
            nimAddStrStr(result_33556535[0], [10]);;
            res_687865871 -= 1;
          }
      };
    };

  return result_33556535[0];

}

function rawWriteStackTrace_u0__system() {
  var result_33556625 = [];

    if (!((framePtr == null))) {
    result_33556625 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10]).concat(auxWriteStackTrace_u0__system(framePtr)), NTI33554449);
    }
    else {
      result_33556625 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556625;

}

function unhandledException(e_p0) {
    var buf_33556666 = [[]];
    if (!(((e_p0.message).length == 0))) {
    nimAddStrStr(buf_33556666[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    nimAddStrStr(buf_33556666[0], e_p0.message);;
    }
    else {
    nimAddStrStr(buf_33556666[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    nimAddStrStr(buf_33556666[0], [32,91]);;
    add_u4__system(buf_33556666, 0, e_p0.name);
    nimAddStrStr(buf_33556666[0], [93,10]);;
    nimAddStrStr(buf_33556666[0], rawWriteStackTrace_u0__system());;
    var cbuf_33556667 = toJSStr(buf_33556666[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556667);
  }
  else {
    throw cbuf_33556667;
  }
  

  
}

function raiseDefect() {
    if (isNimException_u0__system()) {
    var e_33556672 = getCurrentException();
    if (isObj(e_33556672.m_type, NTI33555176)) {
    if ((excHandler == 0)) {
    unhandledException(e_33556672);
    }
    
    e_33556672.trace = nimCopy(null, rawWriteStackTrace_u0__system(), NTI33554449);
    throw e_33556672;
    }
    
    }
    

  
}

function HEX3Aanonymous_u0__jscore95examples953() {
  var F = {procname: "jscore_examples_3.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
  framePtr = F;
    F.line = 153;
    F.filename = "jscore.nim";
    rawEcho([77,105,99,114,111,116,97,115,107]);
  framePtr = F.prev;

  
}
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
F.line = 153;
F.filename = "jscore.nim";
queueMicrotask(HEX3Aanonymous_u0__jscore95examples953);
framePtr = F.prev;
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
