#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/js/jscore.nim(119, 5)
rdoccmd: 
]#
import "/home/runner/work/Nim/Nim/lib/js/jscore.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/js/jscore.nim", 119, 5).}:
  assert ['a', 'b', 'c', 'd', 'e'].copyWithin(0, 3, 4) == @['d', 'b', 'c', 'd', 'e']
  assert ['a', 'b', 'c', 'd', 'e'].copyWithin(1, 3) == @['a', 'd', 'e', 'd', 'e']
  assert [1, 2, 3, 4, 5].copyWithin(-2) == @[1, 2, 3, 1, 2]
  assert [1, 2, 3, 4, 5].copyWithin(0, 3) == @[4, 5, 3, 4, 5]
  assert [1, 2, 3, 4, 5].copyWithin(0, 3, 4) == @[4, 2, 3, 4, 5]
  assert [1, 2, 3, 4, 5].copyWithin(-2, -3, -1) == @[1, 2, 3, 3, 4]

