# autogenerated by docgen
# source: /home/runner/work/Nim/Nim/lib/js/jsffi.nim
# rdoccmd: 
import "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsffi_examples_1.nim"
import "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jsffi_examples_2.nim"
