#[
autogenerated by docgen
loc: /home/runner/work/Nim/Nim/lib/std/private/jsutils.nim(64, 3)
rdoccmd: 
]#
import std/assertions
import "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim"
{.line: ("/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", 64, 3).}:
  let a {.importjs: "Number.MAX_SAFE_INTEGER".}: int64
  assert a == maxSafeInteger

