/* Generated by Nim Compiler v2.3.1 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -fno-strict-aliasing -pthread   -I/home/araq/projects/nim/lib -I/home/araq/projects/nim/lib -o /home/araq/projects/nim/nifcache/@msystem@sexceptions.nim.c.o /home/araq/projects/nim/nifcache/@msystem@sexceptions.nim.c */
#define NIM_INTBITS 64
#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg;
typedef struct tyObject_RefHeader__Z9bCGEWqVeziKrJvotPgwCw tyObject_RefHeader__Z9bCGEWqVeziKrJvotPgwCw;
typedef struct tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA;
typedef struct tyObject_ArithmeticDefect__oPSwDsHz2rNFGLdgOzeW8Q tyObject_ArithmeticDefect__oPSwDsHz2rNFGLdgOzeW8Q;
typedef struct tyObject_Defect__4F9aFUip2NFU61Hinq7r2JA tyObject_Defect__4F9aFUip2NFU61Hinq7r2JA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__tPJeVH9aTsYcKizdxGtv2kg tySequence__tPJeVH9aTsYcKizdxGtv2kg;
typedef struct tySequence__tPJeVH9aTsYcKizdxGtv2kg_Content tySequence__tPJeVH9aTsYcKizdxGtv2kg_Content;
typedef struct tyObject_GcEnv__AkMRdlSmdoc6efLmM9bqnXw tyObject_GcEnv__AkMRdlSmdoc6efLmM9bqnXw;
typedef struct tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__8NhBJbJ1686g09bdXIK8jxA tyObject_CellSeq__8NhBJbJ1686g09bdXIK8jxA;
typedef struct tyTuple__dst3KTd8r9bmwNNya9aMqTuQ tyTuple__dst3KTd8r9bmwNNya9aMqTuQ;
typedef struct tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A;
typedef struct tyObject_StackTraceEntry__wxhPrgsSmSlfTT5wD6tteA tyObject_StackTraceEntry__wxhPrgsSmSlfTT5wD6tteA;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__Z9bCGEWqVeziKrJvotPgwCw {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__tPJeVH9aTsYcKizdxGtv2kg {
	NI len;
	tySequence__tPJeVH9aTsYcKizdxGtv2kg_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__tPJeVH9aTsYcKizdxGtv2kg trace;
	Exception* up;
};
struct tyObject_Defect__4F9aFUip2NFU61Hinq7r2JA {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__oPSwDsHz2rNFGLdgOzeW8Q {
	tyObject_Defect__4F9aFUip2NFU61Hinq7r2JA Sup;
};
struct tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA {
	tyObject_ArithmeticDefect__oPSwDsHz2rNFGLdgOzeW8Q Sup;
};
struct tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__8NhBJbJ1686g09bdXIK8jxA {
	NI len;
	NI cap;
	tyTuple__dst3KTd8r9bmwNNya9aMqTuQ* d;
};
struct tyObject_GcEnv__AkMRdlSmdoc6efLmM9bqnXw {
	tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg traceStack;
	tyObject_CellSeq__8NhBJbJ1686g09bdXIK8jxA toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A {
	tyObject_Defect__4F9aFUip2NFU61Hinq7r2JA Sup;
};
struct tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg {
	tyObject_Defect__4F9aFUip2NFU61Hinq7r2JA Sup;
};
struct tyObject_StackTraceEntry__wxhPrgsSmSlfTT5wD6tteA {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__tPJeVH9aTsYcKizdxGtv2kg_Content {
	NI cap;
	tyObject_StackTraceEntry__wxhPrgsSmSlfTT5wD6tteA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4692)(tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3556)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__Z9bCGEWqVeziKrJvotPgwCw* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5101)(tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3756)(tySequence__tPJeVH9aTsYcKizdxGtv2kg dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5113)(tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3077)(tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3085)(tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4494)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4623)(tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4635)(tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4704)(tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__s1nLbgNqY3aUaZlYeHHI9bg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__BhGPyCk0KjuVemV5aAwWaA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__F7mBJdOKpKw5qsyyvU6W3A_;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4276;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[5] = {3701606400, 1285336064, 1598378496, 4105178624, 294635520};
extern NIM_THREADVAR TFrame* framePtr__system_u2800;
N_LIB_PRIVATE TNimTypeV2 NTIv2__BhGPyCk0KjuVemV5aAwWaA_ = {.destructor = ((void*) rttiDestroy__systemZexceptions_u58), .size = sizeof(tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA), .align = ((NI16) NIM_ALIGNOF(tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA)), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = ((void*) eqtrace___system_u5113), .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 1598378496, 3112248576};
N_LIB_PRIVATE TNimTypeV2 NTIv2__F7mBJdOKpKw5qsyyvU6W3A_ = {.destructor = ((void*) rttiDestroy__systemZexceptions_u62), .size = sizeof(tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A), .align = ((NI16) NIM_ALIGNOF(tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A)), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = ((void*) eqtrace___system_u4635), .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 1598378496, 1506504192};
N_LIB_PRIVATE TNimTypeV2 NTIv2__s1nLbgNqY3aUaZlYeHHI9bg_ = {.destructor = ((void*) rttiDestroy__systemZexceptions_u56), .size = sizeof(tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg), .align = ((NI16) NIM_ALIGNOF(tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg)), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = ((void*) eqtrace___system_u4704), .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
result = ((NI) (((NU) (((NU64) ((NU) (x_p0))) - ((NU64) ((NU) (y_p1)))))));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5101)(tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA* dest_p0) {
	{
	NIM_BOOL T3_;
T3_ = ((NIM_BOOL) 0);
T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
if ((!(T3_))) {
	goto LA4_;
}
nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
}
LA4_: ;
eqdestroy___system_u3756((*dest_p0).Sup.Sup.Sup.trace);
if (((*dest_p0).Sup.Sup.Sup.message.p && (!(((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG))))) {
	deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
{
	NIM_BOOL T8_;
T8_ = ((NIM_BOOL) 0);
T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
if ((!(T8_))) {
	goto LA9_;
}
nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
}
LA9_: ;
}

static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
result = ((&nimInErrorMode__system_u4276));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
eqdestroy___system_u5101(((tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA*) (dest_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
result = ((NI) (((NU) (((NU64) ((NU) (x_p0))) + ((NU64) ((NU) (y_p1)))))));
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
	if ((!((framePtr__system_u2800 == ((TFrame*) NIM_NIL))))) {
	goto LA3_;
}
(*s_p0).calldepth = ((NI16) 0);
}
goto LA1_;
LA3_: ;
{
	(*s_p0).calldepth = ((NI16) ((*framePtr__system_u2800).calldepth + ((NI16) 1)));
}
LA1_: ;
(*s_p0).prev = framePtr__system_u2800;
framePtr__system_u2800 = s_p0;
{
	if ((!(((*s_p0).calldepth == ((NI16) 2000))))) {
	goto LA8_;
}
callDepthLimitReached__system_u4494();
}
LA8_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2800 = (*framePtr__system_u2800).prev;
}

static N_INLINE(void, add__system_u3077)(tyObject_CellSeq__ru4dcYBXdpJMlFUqtSXovg* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
TNimTypeV2* colontmp__2;
	nimfr_("add", "/home/araq/projects/nim/lib/system/cellseqs_v2.nim");
	nimlf_(28, "/home/araq/projects/nim/lib/system/cellseqs_v2.nim");{
	if ((!(((*s_p0).cap <= (*s_p0).len)))) {
	goto LA3_;
}
		nimln_(29);resize__system_u3085(s_p0);
}
LA3_: ;
	nimln_(30);colontmp_ = c_p1;
colontmp__2 = t_p2;
(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI) 1));
	popFrame();
}

static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "/home/araq/projects/nim/lib/system/orc.nim");
	nimlf_(138, "/home/araq/projects/nim/lib/system/orc.nim");p_1 = ((void**) (q_p0));
	nimln_(139);{
	tyObject_GcEnv__AkMRdlSmdoc6efLmM9bqnXw* j_1;
if ((!((!(((*p_1) == NIM_NIL)))))) {
	goto LA3_;
}
		nimln_(140);j_1 = ((tyObject_GcEnv__AkMRdlSmdoc6efLmM9bqnXw*) (env_p1));
		nimln_(141);add__system_u3077(((&(*j_1).traceStack)), p_1, (*((TNimTypeV2**) ((*p_1)))));
}
LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5113)(tyObject_OverflowDefect__BhGPyCk0KjuVemV5aAwWaA* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.parent), env_p1);
nimTraceRefDyn((&(*dest_p0).Sup.Sup.Sup.up), env_p1);
}

N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4623)(tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A* dest_p0) {
	{
	NIM_BOOL T3_;
T3_ = ((NIM_BOOL) 0);
T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
if ((!(T3_))) {
	goto LA4_;
}
nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
}
LA4_: ;
eqdestroy___system_u3756((*dest_p0).Sup.Sup.trace);
if (((*dest_p0).Sup.Sup.message.p && (!(((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG))))) {
	deallocShared((*dest_p0).Sup.Sup.message.p);
}
{
	NIM_BOOL T8_;
T8_ = ((NIM_BOOL) 0);
T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
if ((!(T8_))) {
	goto LA9_;
}
nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
}
LA9_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
eqdestroy___system_u4623(((tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A*) (dest_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4635)(tyObject_RangeDefect__F7mBJdOKpKw5qsyyvU6W3A* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.parent), env_p1);
nimTraceRefDyn((&(*dest_p0).Sup.Sup.up), env_p1);
}

static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "/home/araq/projects/nim/lib/system/orc.nim");
	nimln_(518);result = NIM_FALSE;
	nimln_(519);{
	tyObject_RefHeader__Z9bCGEWqVeziKrJvotPgwCw* cell_1;
NI T5_;
if ((!((!((p_p0 == NIM_NIL)))))) {
	goto LA3_;
}
		nimln_(520);		nimlf_(60, "/home/araq/projects/nim/lib/system/arc.nim");T5_ = ((NI) 0);
T5_ = minuspercent___system_u813(((NI) ((ptrdiff_t) (p_p0))), ((NI) 16));
cell_1 = ((tyObject_RefHeader__Z9bCGEWqVeziKrJvotPgwCw*) (T5_));
		nimlf_(521, "/home/araq/projects/nim/lib/system/orc.nim");{
	if ((!((((NI) ((*cell_1).rc & ((NI) -16))) == ((NI) 0))))) {
	goto LA8_;
}
			nimln_(522);result = NIM_TRUE;
}
goto LA6_;
LA8_: ;
{
				nimln_(525);(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI) 16));
}
LA6_: ;
		nimln_(527);rememberCycle__system_u3556(result, cell_1, (*((TNimTypeV2**) (p_p0))));
}
LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4692)(tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg* dest_p0) {
	{
	NIM_BOOL T3_;
T3_ = ((NIM_BOOL) 0);
T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
if ((!(T3_))) {
	goto LA4_;
}
nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
}
LA4_: ;
eqdestroy___system_u3756((*dest_p0).Sup.Sup.trace);
if (((*dest_p0).Sup.Sup.message.p && (!(((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG))))) {
	deallocShared((*dest_p0).Sup.Sup.message.p);
}
{
	NIM_BOOL T8_;
T8_ = ((NIM_BOOL) 0);
T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
if ((!(T8_))) {
	goto LA9_;
}
nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
}
LA9_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
	NIM_BOOL* nimErr_;
{
		nimErr_ = nimErrorFlag();
eqdestroy___system_u4692(((tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg*) (dest_p0)));
if (NIM_UNLIKELY((*nimErr_))) {
	goto BeforeRet_;
}
}
	BeforeRet_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4704)(tyObject_IndexDefect__s1nLbgNqY3aUaZlYeHHI9bg* dest_p0, void* env_p1) {
	nimTraceRefDyn((&(*dest_p0).Sup.Sup.parent), env_p1);
nimTraceRefDyn((&(*dest_p0).Sup.Sup.up), env_p1);
}

