switch("noNimblePath")
switch("nimblePath", "$projectdir/nimbleDir/simplePkgs")
switch("path", "$nimblepath/pkgA-0.1.0")
switch("path", "$nimblepath/pkgB-#head")
switch("path", "$nimblepath/pkgC-#head")
