import std/[strutils, tables]
import model

type
  NativeArtifactError* = object of ValueError

func nimIdentifier(value: string): string =
  "`" & value.replace("`", "") & "`"

proc typeNames(api: NativeApi): Table[string, string] =
  for typ in api.types:
    result[typ.nifSymbol] = typ.name
    result[typ.typeId] = typ.name

func builtinTypeId(symbol: string): string =
  if not symbol.startsWith("`t"):
    return
  let dot = symbol.find('.')
  if dot < 3:
    return
  case parseInt(symbol[2 ..< dot])
  of 1: "bool"
  of 2: "char"
  of 26: "pointer"
  of 28: "string"
  of 29: "cstring"
  of 31: "int"
  of 32: "int8"
  of 33: "int16"
  of 34: "int32"
  of 35: "int64"
  of 36: "float"
  of 37: "float32"
  of 38: "float64"
  of 40: "uint"
  of 41: "uint8"
  of 42: "uint16"
  of 43: "uint32"
  of 44: "uint64"
  else: ""

proc nimType(symbol: string; names: Table[string, string]): string =
  if symbol.len == 0:
    return ""
  if symbol in names:
    return names[symbol]
  let builtin = builtinTypeId(symbol)
  if builtin.len > 0:
    return builtin
  let dot = symbol.find('.')
  let name = if dot < 0: symbol else: symbol[0 ..< dot]
  case name
  of "bool", "char", "string", "cstring", "pointer",
      "int", "int8", "int16", "int32", "int64",
      "uint", "uint8", "uint16", "uint32", "uint64",
      "float", "float32", "float64",
      "cchar", "cschar", "cshort", "cint", "clong", "clonglong",
      "cuchar", "cushort", "cuint", "culong", "culonglong",
      "cfloat", "cdouble", "csize_t":
    result = name
  else:
    raise newException(NativeArtifactError,
      "unsupported native ABI type symbol: " & symbol)

proc generateTypes(api: NativeApi; names: Table[string, string]): string =
  if api.types.len == 0:
    return
  result.add "type\n"
  for typ in api.types:
    result.add "  " & nimIdentifier(typ.name) & "* = "
    case typ.kind
    of ntObject: result.add "object\n"
    of ntRefObject: result.add "ref object\n"
    for field in typ.fields:
      result.add "    " & nimIdentifier(field.name)
      if field.exported:
        result.add "*"
      result.add ": " & nimType(field.typeSymbol, names) & "\n"
    result.add "\n"

func params(procInfo: NativeProc; names: Table[string, string]): string =
  var parts: seq[string] = @[]
  for param in procInfo.params:
    parts.add nimIdentifier(param.name) & ": " & nimType(param.typeSymbol, names)
  result = parts.join("; ")

func args(procInfo: NativeProc): string =
  var parts: seq[string] = @[]
  for param in procInfo.params:
    parts.add nimIdentifier(param.name)
  result = parts.join(", ")

proc generateNativeModule*(api: NativeApi; libraryPath: string): string =
  if api.procs.len == 0:
    raise newException(NativeArtifactError, "no native ABI exports found")
  let names = typeNames(api)
  result.add "# Generated by nim_native_dynlib; do not edit.\n\n"
  result.add "const nativeLibrary* = " & libraryPath.escape & "\n\n"
  result.add generateTypes(api, names)
  result.add "var nativeLibraryInitialized = false\n\n"
  result.add "proc nativeNimMain() {.cdecl, importc: \"NimMain\", " &
    "dynlib: nativeLibrary.}\n\n"
  result.add "proc initNativeLibrary*() =\n"
  result.add "  if not nativeLibraryInitialized:\n"
  result.add "    nativeNimMain()\n"
  result.add "    nativeLibraryInitialized = true\n"

  for i, procInfo in api.procs:
    let returnType = nimType(procInfo.returnTypeSymbol, names)
    let returnDecl = if returnType.len == 0: "" else: ": " & returnType
    let formals = params(procInfo, names)
    let callArgs = args(procInfo)
    result.add "\nproc nativeRaw" & $i & "(" & formals & ")" & returnDecl &
      " {.nimcall, importc: " & procInfo.cSymbol.escape &
      ", dynlib: nativeLibrary.}\n"
    result.add "\nproc " & nimIdentifier(procInfo.name) & "*(" & formals & ")" &
      returnDecl & " =\n"
    result.add "  initNativeLibrary()\n"
    if returnType.len == 0:
      result.add "  nativeRaw" & $i & "(" & callArgs & ")\n"
    else:
      result.add "  result = nativeRaw" & $i & "(" & callArgs & ")\n"
