# Generated by detect.nim

when defined(linux) and defined(amd64):
  include fcntl/linux_amd64_types
  include fcntl/linux_amd64_consts
  include fcntl/linux_amd64_procs
else:
  include fcntl/other_types
  include fcntl/other_consts
  include fcntl/other_procs
