------------------------ MODULE alloc_focused ------------------------
(*
Focused TLA+ model targeting the specific race condition:
"Chunk freed while foreign thread is adding cells to its shared list"

Simplified scenario:
- Thread T1 owns chunk C
- Thread T1 frees C (thinks foreignCells = 0)
- Thread T2 simultaneously deallocates a cell from C
- Cell goes to T1's sharedFreeLists[size]
- But C is already freed → memory leak

This is the most dangerous race condition in the allocator.
*)

EXTENDS Naturals, Sequences

CONSTANTS T1, T2  (* Two threads *)

(*--algorithm focused

variables
    (* Chunk state *)
    chunkOwner = T1,          (* T1 owns the chunk *)
    chunkFreed = FALSE,        (* Has chunk been freed? *)
    chunkForeignCells = 0,     (* Count of foreign cells in chunk *)
    chunkFreeList = <<2>>,     (* Start with a dummy cell (2) in free list *)

    (* Shared state *)
    sharedFreeList = <<>>,     (* T1's shared free list *)

    (* Cell tracking - cell 1 is allocated by T2, came from T1's chunk *)
    cell1InSharedList = FALSE,
    cell1InChunkList = FALSE,
    cell1Allocated = TRUE,     (* Cell1 is currently allocated (being used by T2) *)
    cell1Owner = T1;           (* Cell belongs to T1's chunk *)

define
    (* CRITICAL INVARIANT: If chunk is freed, no cells can be in shared list waiting to return to it *)
    NoLeakInvariant ==
        chunkFreed => (Len(sharedFreeList) = 0)

    (* If chunk is freed, foreign cells must be zero *)
    ForeignCellsZeroWhenFreed ==
        chunkFreed => (chunkForeignCells = 0)

    (* Cell cannot be in multiple places *)
    CellUnique ==
        (IF cell1InSharedList THEN 1 ELSE 0) +
        (IF cell1InChunkList THEN 1 ELSE 0) +
        (IF cell1Allocated THEN 1 ELSE 0) <= 1
end define;

(*
 * Thread T1: Tries to free its chunk
 *)
fair process Thread1 = T1
begin
    T1_CheckFree:
        (* Check if chunk is completely free *)
        if Len(chunkFreeList) > 0 /\ chunkForeignCells = 0 then
            (* Looks safe to free! *)
            T1_FreeChunk:
                (* But wait! T2 might be adding to sharedFreeList concurrently! *)
                chunkOwner := 0;
                chunkFreed := TRUE;
                chunkFreeList := <<>>;
        end if;
end process;

(*
 * Thread T2: Deallocates a cell that belongs to T1's chunk
 *)
fair process Thread2 = T2
begin
    T2_Dealloc:
        (* Deallocating cell1, which was allocated from T1's chunk *)
        cell1Allocated := FALSE;

    T2_CheckOwner:
        (* Check who owns the chunk - this read is NOT atomic with the free check! *)
        if chunkOwner = T1 then
            (* T1 owns it, so add to T1's shared list *)
            T2_AddToShared:
                sharedFreeList := Append(sharedFreeList, 1);
                cell1InSharedList := TRUE;
        end if;
end process;

(*
 * Thread T1 (alternate action): Processes its shared list
 *)
fair process Thread1_Fetch = T1 + 100
begin
    T1_FetchShared:
        if Len(sharedFreeList) > 0 then
            (* Fetch cells from shared list *)
            await ~chunkFreed;  (* Can't fetch if chunk is freed! *)

            T1_ProcessShared:
                chunkFreeList := chunkFreeList \o sharedFreeList;
                cell1InSharedList := FALSE;
                cell1InChunkList := TRUE;
                sharedFreeList := <<>>;
        end if;
end process;

end algorithm; *)

\* BEGIN TRANSLATION (automatically generated by pcal)
VARIABLES pc, chunkOwner, chunkFreed, chunkForeignCells, chunkFreeList, 
          sharedFreeList, cell1InSharedList, cell1InChunkList, cell1Allocated, 
          cell1Owner

(* define statement *)
NoLeakInvariant ==
    chunkFreed => (Len(sharedFreeList) = 0)


ForeignCellsZeroWhenFreed ==
    chunkFreed => (chunkForeignCells = 0)


CellUnique ==
    (IF cell1InSharedList THEN 1 ELSE 0) +
    (IF cell1InChunkList THEN 1 ELSE 0) +
    (IF cell1Allocated THEN 1 ELSE 0) <= 1


vars == << pc, chunkOwner, chunkFreed, chunkForeignCells, chunkFreeList, 
           sharedFreeList, cell1InSharedList, cell1InChunkList, 
           cell1Allocated, cell1Owner >>

ProcSet == {T1} \cup {T2} \cup {T1 + 100}

Init == (* Global variables *)
        /\ chunkOwner = T1
        /\ chunkFreed = FALSE
        /\ chunkForeignCells = 0
        /\ chunkFreeList = <<2>>
        /\ sharedFreeList = <<>>
        /\ cell1InSharedList = FALSE
        /\ cell1InChunkList = FALSE
        /\ cell1Allocated = TRUE
        /\ cell1Owner = T1
        /\ pc = [self \in ProcSet |-> CASE self = T1 -> "T1_CheckFree"
                                        [] self = T2 -> "T2_Dealloc"
                                        [] self = T1 + 100 -> "T1_FetchShared"]

T1_CheckFree == /\ pc[T1] = "T1_CheckFree"
                /\ IF Len(chunkFreeList) > 0 /\ chunkForeignCells = 0
                      THEN /\ pc' = [pc EXCEPT ![T1] = "T1_FreeChunk"]
                      ELSE /\ pc' = [pc EXCEPT ![T1] = "Done"]
                /\ UNCHANGED << chunkOwner, chunkFreed, chunkForeignCells, 
                                chunkFreeList, sharedFreeList, 
                                cell1InSharedList, cell1InChunkList, 
                                cell1Allocated, cell1Owner >>

T1_FreeChunk == /\ pc[T1] = "T1_FreeChunk"
                /\ chunkOwner' = 0
                /\ chunkFreed' = TRUE
                /\ chunkFreeList' = <<>>
                /\ pc' = [pc EXCEPT ![T1] = "Done"]
                /\ UNCHANGED << chunkForeignCells, sharedFreeList, 
                                cell1InSharedList, cell1InChunkList, 
                                cell1Allocated, cell1Owner >>

Thread1 == T1_CheckFree \/ T1_FreeChunk

T2_Dealloc == /\ pc[T2] = "T2_Dealloc"
              /\ cell1Allocated' = FALSE
              /\ pc' = [pc EXCEPT ![T2] = "T2_CheckOwner"]
              /\ UNCHANGED << chunkOwner, chunkFreed, chunkForeignCells, 
                              chunkFreeList, sharedFreeList, cell1InSharedList, 
                              cell1InChunkList, cell1Owner >>

T2_CheckOwner == /\ pc[T2] = "T2_CheckOwner"
                 /\ IF chunkOwner = T1
                       THEN /\ pc' = [pc EXCEPT ![T2] = "T2_AddToShared"]
                       ELSE /\ pc' = [pc EXCEPT ![T2] = "Done"]
                 /\ UNCHANGED << chunkOwner, chunkFreed, chunkForeignCells, 
                                 chunkFreeList, sharedFreeList, 
                                 cell1InSharedList, cell1InChunkList, 
                                 cell1Allocated, cell1Owner >>

T2_AddToShared == /\ pc[T2] = "T2_AddToShared"
                  /\ sharedFreeList' = Append(sharedFreeList, 1)
                  /\ cell1InSharedList' = TRUE
                  /\ pc' = [pc EXCEPT ![T2] = "Done"]
                  /\ UNCHANGED << chunkOwner, chunkFreed, chunkForeignCells, 
                                  chunkFreeList, cell1InChunkList, 
                                  cell1Allocated, cell1Owner >>

Thread2 == T2_Dealloc \/ T2_CheckOwner \/ T2_AddToShared

T1_FetchShared == /\ pc[T1 + 100] = "T1_FetchShared"
                  /\ IF Len(sharedFreeList) > 0
                        THEN /\ ~chunkFreed
                             /\ pc' = [pc EXCEPT ![T1 + 100] = "T1_ProcessShared"]
                        ELSE /\ pc' = [pc EXCEPT ![T1 + 100] = "Done"]
                  /\ UNCHANGED << chunkOwner, chunkFreed, chunkForeignCells, 
                                  chunkFreeList, sharedFreeList, 
                                  cell1InSharedList, cell1InChunkList, 
                                  cell1Allocated, cell1Owner >>

T1_ProcessShared == /\ pc[T1 + 100] = "T1_ProcessShared"
                    /\ chunkFreeList' = chunkFreeList \o sharedFreeList
                    /\ cell1InSharedList' = FALSE
                    /\ cell1InChunkList' = TRUE
                    /\ sharedFreeList' = <<>>
                    /\ pc' = [pc EXCEPT ![T1 + 100] = "Done"]
                    /\ UNCHANGED << chunkOwner, chunkFreed, chunkForeignCells, 
                                    cell1Allocated, cell1Owner >>

Thread1_Fetch == T1_FetchShared \/ T1_ProcessShared

(* Allow infinite stuttering to prevent deadlock on termination. *)
Terminating == /\ \A self \in ProcSet: pc[self] = "Done"
               /\ UNCHANGED vars

Next == Thread1 \/ Thread2 \/ Thread1_Fetch
           \/ Terminating

Spec == /\ Init /\ [][Next]_vars
        /\ WF_vars(Thread1)
        /\ WF_vars(Thread2)
        /\ WF_vars(Thread1_Fetch)

Termination == <>(\A self \in ProcSet: pc[self] = "Done")

\* END TRANSLATION

====================================================================

(*
This focused model should immediately show the race condition:

COUNTEREXAMPLE TRACE:
1. Initial state: cell1 allocated, chunkFreeList = <<>>, foreignCells = 0
2. T2: Dealloc cell1 (cell1Allocated = FALSE)
3. T1: CheckFree passes (chunkFreeList empty but we have 1 cell coming)
4. T1: FreeChunk (chunkFreed = TRUE)
5. T2: AddToShared (sharedFreeList = <<1>>)
6. INVARIANT VIOLATED: chunkFreed = TRUE but Len(sharedFreeList) = 1

The problem: T1 checks chunkForeignCells = 0, which is true at that moment,
but T2 is in the middle of returning a cell. The cell hasn't been counted yet
because it's in flight through the shared list.

SOLUTION: The check at T1_CheckFree needs to also consider pending shared list entries.
But this requires either:
a) Atomic read of both chunkForeignCells and sharedFreeList
b) Epoch-based reclamation (can't free until all threads have quiesced)
c) Never free chunks (only reuse them)
*)
