switch("styleCheck", "usages")
switch("styleCheck", "error")
switch("define", "nimPreviewSlimSystem")
switch("define", "nimPreviewCstringConversion")
switch("define", "nimPreviewProcConversion")
switch("warningAserror", "ProveInit")
switch("warningAserror", "Uninit")
switch("define", "nimThreadsStrictRaises:off")
