import std/[strutils]
import bifexports

type
  DynlibArtifacts* = object
    cHeader*: string
    nimModule*: string

func sanitizeIdentifier(value: string): string =
  for c in value:
    if c in {'a'..'z', 'A'..'Z', '0'..'9', '_'}:
      result.add c
    else:
      result.add '_'
  if result.len == 0:
    result = "dynlib"
  elif result[0] in {'0'..'9'}:
    result.insert("dynlib_", 0)

func capitalizeAscii(value: string): string =
  result = value
  if result.len > 0 and result[0] in {'a'..'z'}:
    result[0] = chr(ord(result[0]) - ord('a') + ord('A'))

func nimIdentifier(value: string): string =
  "`" & value.replace("`", "") & "`"

func cParams(params: openArray[DynlibParam]): string =
  if params.len == 0:
    return "void"
  var parts: seq[string] = @[]
  for param in params:
    parts.add param.cType & " " & sanitizeIdentifier(param.name)
  result = parts.join(", ")

func nimParams(params: openArray[DynlibParam]): string =
  var parts: seq[string] = @[]
  for param in params:
    parts.add nimIdentifier(param.name) & ": " & param.nimType
  result = parts.join("; ")

func callArgs(params: openArray[DynlibParam]): string =
  var parts: seq[string] = @[]
  for param in params:
    parts.add nimIdentifier(param.name)
  result = parts.join(", ")

func makeCHeader(exports: openArray[DynlibExport]; apiName: string): string =
  let guard = "NIMDYN_" & sanitizeIdentifier(apiName).toUpperAscii & "_H"
  result.add "#ifndef " & guard & "\n"
  result.add "#define " & guard & "\n\n"
  result.add "#include <stddef.h>\n\n"
  result.add "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
  result.add "void NimMain(void);\n"
  let cApiName = sanitizeIdentifier(apiName)
  for i, item in exports:
    result.add "#define " & cApiName & "_" & sanitizeIdentifier(item.nimName) &
      "_" & $i & " " & item.externalName & "\n"
    result.add item.returnCType & " " & item.externalName & "(" &
      cParams(item.params) & ");\n"
  result.add "\n#ifdef __cplusplus\n}\n#endif\n\n"
  result.add "#endif\n"

func makeNimModule(exports: openArray[DynlibExport]; apiName,
                   libraryName: string): string =
  let base = sanitizeIdentifier(apiName)
  let cap = capitalizeAscii(base)
  let libraryConst = base & "Library"
  let initializedVar = base & "Initialized"
  let initRaw = "nimdynInit" & cap
  let initPublic = "init" & cap & "Dynlib"

  result.add "# Generated by icdynlib.\n\n"
  result.add "const " & libraryConst & "* = " & libraryName.escape & "\n\n"
  result.add "var " & initializedVar & " = false\n\n"
  result.add "proc " & initRaw & "() {.cdecl, importc: \"NimMain\", dynlib: " &
    libraryConst & ".}\n\n"
  result.add "proc " & initPublic & "*() =\n"
  result.add "  if not " & initializedVar & ":\n"
  result.add "    " & initRaw & "()\n"
  result.add "    " & initializedVar & " = true\n"

  for i, item in exports:
    let rawName = "nimdynRaw" & $i
    let formals = nimParams(item.params)
    let returnDecl =
      if item.returnNimType.len == 0: ""
      else: ": " & item.returnNimType
    let args = callArgs(item.params)
    result.add "\nproc " & rawName & "(" & formals & ")" & returnDecl &
      " {.cdecl, importc: " & item.externalName.escape & ", dynlib: " &
      libraryConst & ".}\n"
    result.add "\nproc " & nimIdentifier(item.nimName) & "*(" & formals & ")" &
      returnDecl & " =\n"
    result.add "  " & initPublic & "()\n"
    if item.returnNimType.len == 0:
      result.add "  " & rawName & "(" & args & ")\n"
    else:
      result.add "  result = " & rawName & "(" & args & ")\n"

proc generateDynlibArtifacts*(exports: openArray[DynlibExport]; apiName,
                              libraryName: string): DynlibArtifacts =
  ## Generates a C header and Nim loading module for validated exports.
  if exports.len == 0:
    raise newException(ValueError, "no dynlib exports found")
  result = DynlibArtifacts(
    cHeader: makeCHeader(exports, apiName),
    nimModule: makeNimModule(exports, apiName, libraryName))
