import std/assertions
import "../../compiler/icnif" / [nifencoder, nifdecoder]
import "../../compiler" / [idents, ast, astalgo, options, pathutils, modulegraphs, modules, msgs, pipelines, syntaxes, sem, llstream, lineinfos]

# This test generates PNode by semchecks test code.
# Then it is used to test icnif/nifencoder and nifdecoder.

const TestCodeDir = currentSourcePath().AbsoluteFile.splitFile().dir / RelativeDir"testcode"

proc newConfigRefForTest(): ConfigRef =
  var conf = newConfigRef()
  conf.setDefaultLibpath()
  conf.searchPaths.add(conf.libpath)
  excl(conf.notes, hintProcessing)
  excl(conf.mainPackageNotes, hintProcessing)
  result = conf

proc newModuleGraphForSem(cache: IdentCache; conf: ConfigRef): ModuleGraph =
  var graph = newModuleGraph(cache, conf)
  graph.setPipeLinePass(SemPass)
  graph.compilePipelineSystemModule()
  result = graph

proc sem(graph: ModuleGraph; path: AbsoluteFile): PNode =
  result = nil

  let fileIdx = fileInfoIdx(graph.config, path)
  var module = newModule(graph, fileIdx)
  registerModule(graph, module)

  var idgen = idGeneratorFromModule(module)
  let ctx = preparePContext(graph, module, idgen)

  var stream = llStreamOpen(path, fmRead)
  if stream == nil:
    rawMessage(graph.config, errCannotOpenFile, path.string)
    return nil

  var p: Parser = default(Parser)
  syntaxes.openParser(p, fileIdx, stream, graph.cache, graph.config)

  checkFirstLineIndentation(p)
  block processCode:
    if graph.stopCompile(): break processCode
    var n = parseTopLevelStmt(p)
    if n.kind == nkEmpty: break processCode
    # read everything, no streaming possible
    var sl = newNodeI(nkStmtList, n.info)
    sl.add n
    while true:
      var n = parseTopLevelStmt(p)
      if n.kind == nkEmpty: break
      sl.add n

    var semNode = semWithPContext(ctx, sl)

    return semNode

const SysTypeKinds = {tyBool, tyChar, tyString, tyInt .. tyUInt64}

type
  # Nim's AST has cycles that causes infinite recursive loop in eql procs.
  # this is used to prevent that happen.
  EqlContext = object
    nodeStack: seq[PNode]
    symStack: seq[PSym]
    typStack: seq[PType]
    conf: ConfigRef   # used to print the line info when there is a mismatch.

# Compare PType, PSym and PNode but ignores fields nifencoder and nifdecoder doesn't support
# Assumes `x` is generated by sem.nim and `y` is decoded by icnif/nifdecoder.
# So `eql(x, y) == eql(y, x)` is not always true.
proc eql(x, y: PNode; c: var EqlContext): bool

proc eql(x, y: TLoc): bool =
  if x.k != y.k:
    echo "loc kind mismatch: ", x.k, "/", y.k
    result = false
  elif x.snippet != y.snippet:
    echo "loc snippet mismatch: ", x.snippet, "/", y.snippet
    result = false
  else:
    result = true

proc eql(x, y: PType; c: var EqlContext): bool =
  if x == nil and y == nil:
    result = true
  elif x == nil or y == nil:
    echo "type is missing"
    result = false
  elif x.kind != y.kind:
    echo "type kind mismatch: ", x.kind, "/", y.kind
    result = false
  elif x.flags != y.flags:
    echo "flag mismatch: ", x.flags, "/", y.flags
    result = false
  else:
    if c.typStack.len != 0:
      for i in countDown(c.typStack.len - 1, 0):
        if x == c.typStack[i]:
          # echo "cycle is detected in PType"
          return true
    c.typStack.add x
    if not eql(x.n, y.n, c):
      echo "type.n mismatch"
      debug(x.n)
      debug(y.n)
      result = false
    elif x.kidsLen != y.kidsLen:
      echo "type kidsLen mismatch"
      result = false
    else:
      result = true
      for i in 0 ..< x.kidsLen:
        if not eql(x[i], y[i], c):
          echo "type kids mismatch: "
          debug(x[i])
          debug(y[i])
          result = false
          break
    discard c.typStack.pop

proc eql(x, y: PSym; c: var EqlContext): bool =
  if x == nil and y == nil:
    result = true
  elif x == nil or y == nil:
    echo "symbol is missing"
    result = false
  elif x.kind != y.kind:
    echo "symbol kind mismatch: ", x.kind, "/", y.kind
    result = false
  elif x.name.s != y.name.s:
    echo "symbol name mismatch: ", x.name.s, "/", y.name.s
    result = false
  elif x.flags != y.flags:
    echo "symbol flag mismatch: ", x.flags, "/", y.flags
    result = false
  elif not eql(x.loc, y.loc):
    echo "symbol.loc mismatch"
    result = false
  elif not (x.kind == skType and x.typ.kind in SysTypeKinds) and
       not (x.itemId.item == y.itemId.item and x.disamb == y.disamb and x.flags == y.flags):
    echo "symbol itemId or disamb mismatch"
    result = false
  elif (x.flags * {sfImportc, sfExportc} != {}) and (x.loc.snippet != y.loc.snippet):
    echo "importc or exportc mismatch: ", x.loc.snippet, "/", y.loc.snippet
    result = false
  else:
    if c.symStack.len != 0:
      for i in countDown(c.symStack.len - 1, 0):
        if x == c.symStack[i]:
          return true
    c.symStack.add x
    if not eql(x.typ, y.typ, c):
      echo "symbol type mismatch: "
      result = false
    else:
      if x.owner == nil and y.owner == nil:
        result = true
      elif x.owner == nil or y.owner == nil:
        echo "missing owner"
        result = false
      elif (x.owner.kind == y.owner.kind and x.owner.name.s == y.owner.name.s) or x.owner.name.s == "system":
        # Current system types in nifdecoder doesn't have system module owner
        if x.kind == skModule:
          result = true
        else:
          result = x.position == y.position
      else:
        echo "Symbol owner mismatch: "
        debug(x.owner)
        debug(y.owner)
        result = false
    discard c.symStack.pop

proc eql(x, y: PNode; c: var EqlContext): bool =
  if x == nil and y == nil:
    result = true
  elif x == nil or y == nil:
    result = false
  elif x.kind != y.kind:
    echo "node kind mismatch: ", x.kind, "/", y.kind
    result = false
  elif x.flags != y.flags:
    echo "node flag mismatch: ", x.flags, "/", y.flags
    debug(x)
    debug(y)
    result = false
  elif x.safeLen == y.safeLen:
    if c.nodeStack.len != 0:
      for i in countDown(c.nodeStack.len - 1, 0):
        if x == c.nodeStack[i]:
          # echo "cycle is detected in PNode"
          return true
    c.nodeStack.add x
    if x.kind != nkNilLit and not eql(x.typ, y.typ, c):
      # ignore node type if it is nil literal.
      # current nifencoder doesn't encode the type of nil lit.
      echo "PNode type mismatch at ", `$`(c.conf, x.info), ":"
      debug(x)
      debug(y)
      debug(x.typ)
      debug(y.typ)
      result = false
    else:
      case x.kind:
      of nkSym:
        result = eql(x.sym, y.sym, c)
        if not result:
          echo "Symbol mismatch:"
          debug(x.sym)
          debug(y.sym)
          debug(x.sym.typ)
          debug(y.sym.typ)
      of nkCharLit .. nkTripleStrLit:
        result = sameValue(x, y)
      of nkIdentDefs:
        assert x.len == 3 and y.len == 3
        if eql(x[0], y[0], c) and
           eql(x[2], y[2], c) and
           y[1].kind == nkEmpty and
           (if y[0].kind == nkPragmaExpr: y[0][0] else: y[0]).sym.typ != nil:
          result = true
        else:
          echo "nkIdentDefs mismatch"
          result = false
      of nkTypeDef:
        assert x.len == 3 and y.len == 3
        if eql(x[0], y[0], c) and eql(x[1], y[1], c):
          let sym = if y[0].kind == nkPostfix:
            y[0][1].sym
          else:
            y[0].sym
          result = y[2].kind == nkEmpty and sym.typ != nil
        else:
          result = false
        if not result:
          echo "nkTypeDef mismatch"
      else:
        result = true
        for i in 0 ..< x.safeLen:
          if not eql(x[i], y[i], c):
            result = false
            break
      discard c.nodeStack.pop
  else:
    echo "node length mismatch"
    debug(x)
    debug(y)
    result = false

proc testNifEncDec(graph: ModuleGraph; src: string) =
  let fullPath = TestCodeDir / RelativeFile(src)
  let n = sem(graph, fullPath)
  #debug(n)
  let nif = saveNifToBuffer(n, graph.config)
  #debug(n[0][0][0].typ)
  #echo nif

  # Don't reuse the ModuleGraph used for semcheck when load NIF.
  var graphForLoad = newModuleGraph(newIdentCache(), newConfigRefForTest())
  let n2 = loadNifFromBuffer(nif, fullPath, graphForLoad)
  #debug(n2)
  var c = EqlContext()
  c.conf = graph.config
  assert eql(n, n2, c)

var conf = newConfigRefForTest()
var cache = newIdentCache()
var graph = newModuleGraphForSem(cache, conf)
testNifEncDec(graph, "modtest1.nim")
testNifEncDec(graph, "modtestliterals.nim")
testNifEncDec(graph, "modtesttypesections.nim")
testNifEncDec(graph, "modtestpragmas.nim")
