import std/assertions
import "../../compiler/icnif" / [nifencoder, nifdecoder]
import "../../compiler" / [idents, ast, astalgo, options, pathutils, modulegraphs, modules, msgs, pipelines, syntaxes, sem, llstream, lineinfos]

# This test generates PNode by semchecks test code.
# Then it is used to test icnif/nifencoder and nifdecoder.

const TestCodeDir = currentSourcePath().AbsoluteFile.splitFile().dir / RelativeDir"testcode"

proc newConfigRefForTest(): ConfigRef =
  var conf = newConfigRef()
  conf.setDefaultLibpath()
  conf.searchPaths.add(conf.libpath)
  excl(conf.notes, hintProcessing)
  excl(conf.mainPackageNotes, hintProcessing)
  result = conf

proc newModuleGraphForSem(cache: IdentCache; conf: ConfigRef): ModuleGraph =
  var graph = newModuleGraph(cache, conf)
  graph.setPipeLinePass(SemPass)
  graph.compilePipelineSystemModule()
  result = graph

proc sem(graph: ModuleGraph; path: AbsoluteFile): PNode =
  result = nil

  let fileIdx = fileInfoIdx(graph.config, path)
  var module = newModule(graph, fileIdx)
  registerModule(graph, module)

  var idgen = idGeneratorFromModule(module)
  let ctx = preparePContext(graph, module, idgen)

  var stream = llStreamOpen(path, fmRead)
  if stream == nil:
    rawMessage(graph.config, errCannotOpenFile, path.string)
    return nil

  var p: Parser = default(Parser)
  syntaxes.openParser(p, fileIdx, stream, graph.cache, graph.config)

  checkFirstLineIndentation(p)
  block processCode:
    if graph.stopCompile(): break processCode
    var n = parseTopLevelStmt(p)
    if n.kind == nkEmpty: break processCode
    # read everything, no streaming possible
    var sl = newNodeI(nkStmtList, n.info)
    sl.add n
    while true:
      var n = parseTopLevelStmt(p)
      if n.kind == nkEmpty: break
      sl.add n

    var semNode = semWithPContext(ctx, sl)

    return semNode

const SysTypeKinds = {tyBool, tyChar, tyString, tyInt .. tyUInt64}

# Compare PType, PSym and PNode but ignores fields nifencoder and nifdecoder doesn't support
# Assumes `x` is generated by sem.nim and `y` is decoded by icnif/nifdecoder.
# So `eql(x, y) == eql(y, x)` is not always true.
proc eql(x, y: PType): bool =
  if x == nil and y == nil:
    result = true
  elif x == nil or y == nil:
    result = false
  elif x.kind == y.kind:
    result = true
  else:
    echo "type kind mismatch: ", x.kind, "/", y.kind
    result = false

proc eql(x, y: PSym): bool =
  if x == nil and y == nil:
    result = true
  elif x == nil or y == nil:
    result = false
  elif x.kind == y.kind and eql(x.typ, y.typ) and x.name.s == y.name.s:
    if (x.itemId.item == y.itemId.item and x.disamb == y.disamb and x.flags == y.flags) or (x.kind == skType and x.typ.kind in SysTypeKinds):
      if x.owner == nil and y.owner == nil:
        result = true
      elif x.owner == nil or y.owner == nil:
        echo "missing owner"
        result = false
      elif (x.owner.kind == y.owner.kind and x.owner.name.s == y.owner.name.s) or x.owner.name.s == "system":
        # Current system types in nifdecoder doesn't have system module owner
        if x.kind == skModule:
          result = true
        else:
          result = x.position == y.position
      else:
        echo "Symbol owner mismatch: "
        debug(x.owner)
        debug(y.owner)
        result = false
    else:
      result = false
  else:
    result = false

proc eql(x, y: PNode): bool =
  if x == nil and y == nil:
    result = true
  elif x == nil or y == nil:
    result = false
  elif x.kind == y.kind and x.safeLen == y.safeLen:
    case x.kind:
    of nkSym:
      result = eql(x.sym, y.sym)
      if not result:
        echo "Symbol mismatch:"
        debug(x.sym)
        debug(y.sym)
        debug(x.sym.typ)
        debug(y.sym.typ)
    of nkCharLit .. nkTripleStrLit:
      result = sameValue(x, y)
    of nkIdentDefs:
      assert x.len == 3 and y.len == 3
      if eql(x[0], y[0]) and eql(x[2], y[2]):
        result = y[1].kind == nkEmpty and y[0].sym.typ != nil
      else:
        result = false
    of nkTypeDef:
      assert x.len == 3 and y.len == 3
      if eql(x[0], y[0]) and eql(x[1], y[1]):
        result = y[2].kind == nkEmpty and y[0].sym.typ != nil
      else:
        result = false
    else:
      result = true
      for i in 0 ..< x.safeLen:
        if not eql(x[i], y[i]):
          result = false
          break
  else:
    result = false

proc testNifEncDec(graph: ModuleGraph; src: string) =
  let fullPath = TestCodeDir / RelativeFile(src)
  let n = sem(graph, fullPath)
  let nif = saveNifToBuffer(n, graph.config)
  #debug(n)
  #echo nif

  # Don't reuse the ModuleGraph used for semcheck when load NIF.
  var graphForLoad = newModuleGraph(newIdentCache(), newConfigRefForTest())
  let n2 = loadNifFromBuffer(nif, fullPath, graphForLoad)
  #debug(n2)
  assert eql(n, n2)

var conf = newConfigRefForTest()
var cache = newIdentCache()
var graph = newModuleGraphForSem(cache, conf)
testNifEncDec(graph, "modtest1.nim")
testNifEncDec(graph, "modtestliterals.nim")
testNifEncDec(graph, "modtesttypesections.nim")
