# Auto-generates import suggestions for the Nim compiler
# Run from Nim repo root: nim c -r tools/gen_import_suggestions.nim

import std/[os, strutils, tables, sets, algorithm, sequtils]
import compiler/[ast, idents, modules, passes, options,
                 modulegraphs, lineinfos, pathutils, condsyms,
                 sem, vmdef, modulepaths, msgs]

proc setupCompilerForScanning(): ModuleGraph =
  # Initialize compiler configuration
  let cache = newIdentCache()
  let conf = newConfigRef()

  # Set up paths
  let nimRoot = getCurrentDir()
  conf.libpath = AbsoluteDir(nimRoot / "lib")
  conf.prefixDir = AbsoluteDir(nimRoot)

  # Minimize output
  conf.errorMax = 0
  conf.verbosity = 0
  conf.notes = {}
  conf.mainPackageNotes = {}
  conf.foreignPackageNotes = {}

  # Create module graph
  result = newModuleGraph(cache, conf)
  initDefines(conf.symbols)

  # Load system module first (required for proper initialization)
  let systemFileIdx = fileInfoIdx(conf, conf.libpath / RelativeFile("system.nim"))
  discard result.compileModule(systemFileIdx, {sfSystemModule})

proc extractExportedSymbols(graph: ModuleGraph, moduleFile: AbsoluteFile): seq[string] =
  result = @[]

  try:
    # Load and compile module
    let fileIdx = fileInfoIdx(graph.config, moduleFile)
    let moduleSym = graph.compileModule(fileIdx, {})

    if moduleSym.isNil:
      return

    # Iterate through module's exported symbols using modulegraphs.allSyms
    for s in modulegraphs.allSyms(graph, moduleSym):
      if s.isNil: continue

      # Skip certain kinds
      if s.kind in {skModule, skPackage, skUnknown, skStub, skEnumField}:
        continue

      # Skip compiler magic/internal stuff
      let name = s.name.s
      if name.len == 0: continue
      if name.startsWith("internal"): continue
      if name.startsWith("`"): continue  # Skip operators for now

      result.add name

  except CatchableError:
    # Module failed to compile - skip it
    discard

proc getModulePath(filePath: string): string =
  # Convert "lib/std/os.nim" -> "std/os"
  # Convert "lib/pure/json.nim" -> "json"
  # Convert "lib/core/typeinfo.nim" -> "typeinfo"
  result = filePath
  result.removePrefix("lib/")
  result.removeSuffix(".nim")

  # For pure/impure/core, strip the directory since they're imported without it
  for prefix in ["pure/", "impure/", "core/"]:
    if result.startsWith(prefix):
      result.removePrefix(prefix)
      break

proc shouldIncludeModule(path: string): bool =
  # Skip unwanted modules
  if "private" in path: return false
  if "internal" in path: return false
  if "/test" in path or "tests/" in path: return false
  if "testament" in path: return false
  if "compiler/" in path: return false
  if "nimsuggest/" in path: return false

  let name = path.splitPath.tail
  if name == "system.nim": return false  # Always imported
  if name.startsWith("test"): return false

  return true

proc generateSuggestions*() =
  echo "Initializing Nim compiler API..."
  let graph = setupCompilerForScanning()

  echo "Scanning lib/ directory..."
  let libPath = getCurrentDir() / "lib"

  var symbolMap: Table[string, seq[string]]  # symbol -> list of modules
  var moduleCount = 0
  var totalSymbols = 0

  for path in walkDirRec(libPath, {pcFile}):
    if not path.endsWith(".nim"): continue
    if not shouldIncludeModule(path): continue

    let relativePath = path.relativePath(getCurrentDir())
    let modulePath = getModulePath(relativePath)
    let absPath = AbsoluteFile(path)

    inc moduleCount
    if moduleCount mod 20 == 0:
      echo "  Processed ", moduleCount, " modules..."

    let symbols = extractExportedSymbols(graph, absPath)

    for symName in symbols:
      inc totalSymbols

      if symName notin symbolMap:
        symbolMap[symName] = @[]

      # Add module if not already present
      if modulePath notin symbolMap[symName]:
        symbolMap[symName].add modulePath

  echo "Found ", symbolMap.len, " unique symbols from ", moduleCount, " modules"
  echo "Total symbol exports: ", totalSymbols

  # Count symbols in multiple modules
  var multiModuleCount = 0
  for modules in symbolMap.values:
    if modules.len > 1:
      inc multiModuleCount
  echo "Symbols in multiple modules: ", multiModuleCount

  # Generate output file
  echo "Generating compiler/suggest_imports.nim..."

  var output = """# Auto-generated by tools/gen_import_suggestions.nim
# Run from Nim repo root: nim c -r tools/gen_import_suggestions.nim
# Do not edit manually

import std/tables

const importSuggestions* = {
"""

  # Sort for deterministic output
  var sortedSymbols = toSeq(symbolMap.pairs)
  sortedSymbols.sort(proc (a, b: auto): int = cmp(a[0], b[0]))

  for (name, modules) in sortedSymbols:
    # Escape the symbol name
    let escapedName = name.multiReplace([("\\", "\\\\"), ("\"", "\\\"")])

    # Format module list
    output.add "  \"$#\": @[" % escapedName
    for i, module in modules:
      let escapedModule = module.multiReplace([("\\", "\\\\"), ("\"", "\\\"")])
      if i > 0:
        output.add ", "
      output.add "\"$#\"" % escapedModule
    output.add "],\n"

  output.add "}.toTable\n"

  writeFile("compiler/suggest_imports.nim", output)

  let fileSize = getFileSize("compiler/suggest_imports.nim")
  echo "Done! Generated compiler/suggest_imports.nim"
  echo "  File size: ", (fileSize div 1024), " KB"
