const Smilies = {
  ":D": "icon_e_biggrin",  # Original Emoji set.
  ":-D": "icon_e_biggrin",
  ":)": "icon_e_smile",
  ":-)": "icon_e_smile",
  ";)": "icon_e_wink",
  ";-)": "icon_e_wink",
  ":(": "icon_e_sad",
  ":-(": "icon_e_sad",
  ":o": "icon_e_surprised",
  ":-o": "icon_e_surprised",
  ":shock:": "icon_eek",
  ":?": "icon_e_confused",
  ":-?": "icon_e_confused",
  ":-/": "icon_e_confused",
  "8-)": "icon_cool",
  ":lol:": "icon_lol",
  ":x": "icon_mad",
  ":-x": "icon_mad",
  ":P": "icon_razz",
  ":-P": "icon_razz",
  ":oops:": "icon_redface",
  ":cry:": "icon_cry",
  ":evil:": "icon_evil",
  ":twisted:": "icon_twisted",
  ":roll:": "icon_rolleyes",
  ":!:": "icon_exclaim",
  ":?:": "icon_question",
  ":idea:": "icon_idea",
  ":arrow:": "icon_arrow",
  ":|": "icon_neutral",
  ":-|": "icon_neutral",
  ":mrgreen:": "icon_mrgreen",
  ":geek:": "icon_e_geek",
  ":ugeek:": "icon_e_ugeek",
  ":orange_heart:": "icon_orange_heart", # v10  \u1f9e1
  ":yellow_heart:": "icon_yellow_heart", # v6  \u1f49b
  ":green_heart:": "icon_green_heart", # v6  \u1f49a
  ":blue_heart:": "icon_blue_heart", # v6  \u1f499
  ":purple_heart:": "icon_purple_heart", # v6  \u1f49c
  ":black_heart:": "icon_black_heart", # v9  \u1f5a4
  ":broken_heart:": "icon_broken_heart", # v6  \u1f494
  ":two_hearts:": "icon_two_hearts", # v6  \u1f495
  ":revolving_hearts:": "icon_revolving_hearts", # v6  \u1f49e
  ":heartbeat:": "icon_heartbeat", # v6  \u1f493
  ":heartpulse:": "icon_heartpulse", # v6  \u1f497
  ":sparkling_heart:": "icon_sparkling_heart", # v6  \u1f496
  ":cupid:": "icon_cupid", # v6  \u1f498
  ":gift_heart:": "icon_gift_heart", # v6  \u1f49d
  ":heart_decoration:": "icon_heart_decoration", # v6  \u1f49f
  ":om_symbol:": "icon_om_symbol", # v7  \u1f549
  ":six_pointed_star:": "icon_six_pointed_star", # v6  \u1f52f
  ":menorah:": "icon_menorah", # v8  \u1f54e
  ":place_of_worship:": "icon_place_of_worship", # v8  \u1f6d0
  ":accept:": "icon_accept", # v6  \u1f251
  ":mobile_phone_off:": "icon_mobile_phone_off", # v6  \u1f4f4
  ":vibration_mode:": "icon_vibration_mode", # v6  \u1f4f3
  ":u6709:": "icon_u6709", # v6  \u1f236
  ":u7121:": "icon_u7121", # v5.2  \u1f21a
  ":u7533:": "icon_u7533", # v6  \u1f238
  ":u55b6:": "icon_u55b6", # v6  \u1f23a
  ":u6708:": "icon_u6708", # v6  \u1f237
  ":white_flower:": "icon_white_flower", # v6  \u1f4ae
  ":ideograph_advantage:": "icon_ideograph_advantage", # v6  \u1f250
  ":u5408:": "icon_u5408", # v6  \u1f234
  ":u6e80:": "icon_u6e80", # v6  \u1f235
  ":u5272:": "icon_u5272", # v6  \u1f239
  ":u7981:": "icon_u7981", # v6  \u1f232
  ":octagonal_sign:": "icon_octagonal_sign", # v9  \u1f6d1
  ":name_badge:": "icon_name_badge", # v6  \u1f4db
  ":no_entry_sign:": "icon_no_entry_sign", # v6  \u1f6ab
  ":anger:": "icon_anger", # v6  \u1f4a2
  ":no_pedestrians:": "icon_no_pedestrians", # v6  \u1f6b7
  ":do_not_litter:": "icon_do_not_litter", # v6  \u1f6af
  ":no_bicycles:": "icon_no_bicycles", # v6  \u1f6b3
  ":non_potable_water:": "icon_non_potable_water", # v6  \u1f6b1
  ":underage:": "icon_underage", # v6  \u1f51e
  ":no_mobile_phones:": "icon_no_mobile_phones", # v6  \u1f4f5
  ":no_smoking:": "icon_no_smoking", # v6  \u1f6ad
  ":low_brightness:": "icon_low_brightness", # v6  \u1f505
  ":high_brightness:": "icon_high_brightness", # v6  \u1f506
  ":children_crossing:": "icon_children_crossing", # v6  \u1f6b8
  ":trident:": "icon_trident", # v6  \u1f531
  ":beginner:": "icon_beginner", # v6  \u1f530
  ":u6307:": "icon_u6307", # v5.2  \u1f22f
  ":chart:": "icon_chart", # v6  \u1f4b9
  ":globe_with_meridians:": "icon_globe_with_meridians", # v6  \u1f310
  ":diamond_shape_with_a_dot_inside:": "icon_diamond_shape_with_a_dot_inside", # v6  \u1f4a0
  ":cyclone:": "icon_cyclone", # v6  \u1f300
  ":parking:": "icon_parking", # v5.2  \u1f17f
  ":u7a7a:": "icon_u7a7a", # v6  \u1f233
  ":passport_control:": "icon_passport_control", # v6  \u1f6c2
  ":customs:": "icon_customs", # v6  \u1f6c3
  ":baggage_claim:": "icon_baggage_claim", # v6  \u1f6c4
  ":left_luggage:": "icon_left_luggage", # v6  \u1f6c5
  ":mens:": "icon_mens", # v6  \u1f6b9
  ":womens:": "icon_womens", # v6  \u1f6ba
  ":baby_symbol:": "icon_baby_symbol", # v6  \u1f6bc
  ":restroom:": "icon_restroom", # v6  \u1f6bb
  ":put_litter_in_its_place:": "icon_put_litter_in_its_place", # v6  \u1f6ae
  ":cinema:": "icon_cinema", # v6  \u1f3a6
  ":signal_strength:": "icon_signal_strength", # v6  \u1f4f6
  ":koko:": "icon_koko", # v6  \u1f201
  ":symbols:": "icon_symbols", # v6  \u1f523
  ":abcd:": "icon_abcd", # v6  \u1f521
  ":capital_abcd:": "icon_capital_abcd", # v6  \u1f520
  ":cool:": "icon_cool", # v6  \u1f192
  ":free:": "icon_free", # v6  \u1f193
  ":keycap_ten:": "icon_keycap_ten", # v6  \u1f51f
  ":1234:": "icon_1234", # v6  \u1f522
  ":arrow_up_small:": "icon_arrow_up_small", # v6  \u1f53c
  ":arrow_down_small:": "icon_arrow_down_small", # v6  \u1f53d
  ":twisted_rightwards_arrows:": "icon_twisted_rightwards_arrows", # v6  \u1f500
  ":repeat:": "icon_repeat", # v6  \u1f501
  ":repeat_one:": "icon_repeat_one", # v6  \u1f502
  ":arrows_counterclockwise:": "icon_arrows_counterclockwise", # v6  \u1f504
  ":arrows_clockwise:": "icon_arrows_clockwise", # v6  \u1f503
  ":musical_note:": "icon_musical_note", # v6  \u1f3b5
  ":notes:": "icon_notes", # v6  \u1f3b6
  ":heavy_dollar_sign:": "icon_heavy_dollar_sign", # v6  \u1f4b2
  ":currency_exchange:": "icon_currency_exchange", # v6  \u1f4b1
  ":back:": "icon_back", # v6  \u1f519
  ":soon:": "icon_soon", # v6  \u1f51c
  ":radio_button:": "icon_radio_button", # v6  \u1f518
  ":red_circle:": "icon_red_circle", # v6  \u1f534
  ":blue_circle:": "icon_blue_circle", # v6  \u1f535
  ":small_red_triangle:": "icon_small_red_triangle", # v6  \u1f53a
  ":small_red_triangle_down:": "icon_small_red_triangle_down", # v6  \u1f53b
  ":small_orange_diamond:": "icon_small_orange_diamond", # v6  \u1f538
  ":small_blue_diamond:": "icon_small_blue_diamond", # v6  \u1f539
  ":large_orange_diamond:": "icon_large_orange_diamond", # v6  \u1f536
  ":large_blue_diamond:": "icon_large_blue_diamond", # v6  \u1f537
  ":white_square_button:": "icon_white_square_button", # v6  \u1f533
  ":black_square_button:": "icon_black_square_button", # v6  \u1f532
  ":speaker:": "icon_speaker", # v6  \u1f508
  ":mute:": "icon_mute", # v6  \u1f507
  ":sound:": "icon_sound", # v6  \u1f509
  ":loud_sound:": "icon_loud_sound", # v6  \u1f50a
  ":bell:": "icon_bell", # v6  \u1f514
  ":no_bell:": "icon_no_bell", # v6  \u1f515
  ":mega:": "icon_mega", # v6  \u1f4e3
  ":loudspeaker:": "icon_loudspeaker", # v6  \u1f4e2
  ":speech_left:": "icon_speech_left", # v7  \u1f5e8
  ":speech_balloon:": "icon_speech_balloon", # v6  \u1f4ac
  ":thought_balloon:": "icon_thought_balloon", # v6  \u1f4ad
  ":anger_right:": "icon_anger_right", # v7  \u1f5ef
  ":black_joker:": "icon_black_joker", # v6  \u1f0cf
  ":flower_playing_cards:": "icon_flower_playing_cards", # v6  \u1f3b4
  ":mahjong:": "icon_mahjong", # v5.1  \u1f004
  ":clock1:": "icon_clock1", # v6  \u1f550
  ":clock2:": "icon_clock2", # v6  \u1f551
  ":clock3:": "icon_clock3", # v6  \u1f552
  ":clock4:": "icon_clock4", # v6  \u1f553
  ":clock5:": "icon_clock5", # v6  \u1f554
  ":clock6:": "icon_clock6", # v6  \u1f555
  ":clock7:": "icon_clock7", # v6  \u1f556
  ":clock8:": "icon_clock8", # v6  \u1f557
  ":clock9:": "icon_clock9", # v6  \u1f558
  ":clock10:": "icon_clock10", # v6  \u1f559
  ":clock11:": "icon_clock11", # v6  \u1f55a
  ":clock12:": "icon_clock12", # v6  \u1f55b
  ":clock130:": "icon_clock130", # v6  \u1f55c
  ":clock230:": "icon_clock230", # v6  \u1f55d
  ":clock330:": "icon_clock330", # v6  \u1f55e
  ":clock430:": "icon_clock430", # v6  \u1f55f
  ":clock530:": "icon_clock530", # v6  \u1f560
  ":clock630:": "icon_clock630", # v6  \u1f561
  ":clock730:": "icon_clock730", # v6  \u1f562
  ":clock830:": "icon_clock830", # v6  \u1f563
  ":clock930:": "icon_clock930", # v6  \u1f564
  ":clock1030:": "icon_clock1030", # v6  \u1f565
  ":clock1130:": "icon_clock1130", # v6  \u1f566
  ":clock1230:": "icon_clock1230", # v6  \u1f567
  ":basketball:": "icon_basketball", # v6  \u1f3c0
  ":football:": "icon_football", # v6  \u1f3c8
  ":softball:": "icon_softball", # v11  \u1f94e
  ":tennis:": "icon_tennis", # v6  \u1f3be
  ":volleyball:": "icon_volleyball", # v8  \u1f3d0
  ":rugby_football:": "icon_rugby_football", # v6  \u1f3c9
  ":8ball:": "icon_8ball", # v6  \u1f3b1
  ":ping_pong:": "icon_ping_pong", # v8  \u1f3d3
  ":badminton:": "icon_badminton", # v8  \u1f3f8
  ":goal:": "icon_goal", # v9  \u1f945
  ":hockey:": "icon_hockey", # v8  \u1f3d2
  ":field_hockey:": "icon_field_hockey", # v8  \u1f3d1
  ":cricket_game:": "icon_cricket_game", # v8  \u1f3cf
  ":lacrosse:": "icon_lacrosse", # v11  \u1f94d
  ":flying_disc:": "icon_flying_disc", # v11  \u1f94f
  ":bow_and_arrow:": "icon_bow_and_arrow", # v8  \u1f3f9
  ":fishing_pole_and_fish:": "icon_fishing_pole_and_fish", # v6  \u1f3a3
  ":boxing_glove:": "icon_boxing_glove", # v9  \u1f94a
  ":martial_arts_uniform:": "icon_martial_arts_uniform", # v9  \u1f94b
  ":running_shirt_with_sash:": "icon_running_shirt_with_sash", # v6  \u1f3bd
  ":skateboard:": "icon_skateboard", # v11  \u1f6f9
  ":sled:": "icon_sled", # v10  \u1f6f7
  ":snowboarder:": "icon_snowboarder", # v6  \u1f3c2
  ":person_lifting_weights:": "icon_person_lifting_weights", # v7  \u1f3cb
  ":people_wrestling:": "icon_people_wrestling", # v9  \u1f93c
  ":person_doing_cartwheel:": "icon_person_doing_cartwheel", # v9  \u1f938
  ":person_fencing:": "icon_person_fencing", # v9  \u1f93a
  ":person_playing_handball:": "icon_person_playing_handball", # v9  \u1f93e
  ":person_golfing:": "icon_person_golfing", # v7  \u1f3cc
  ":horse_racing:": "icon_horse_racing", # v6  \u1f3c7
  ":person_in_lotus_position:": "icon_person_in_lotus_position", # v10  \u1f9d8
  ":person_surfing:": "icon_person_surfing", # v6  \u1f3c4
  ":person_swimming:": "icon_person_swimming", # v6  \u1f3ca
  ":person_playing_water_polo:": "icon_person_playing_water_polo", # v9  \u1f93d
  ":person_rowing_boat:": "icon_person_rowing_boat", # v6  \u1f6a3
  ":person_climbing:": "icon_person_climbing", # v10  \u1f9d7
  ":person_mountain_biking:": "icon_person_mountain_biking", # v6  \u1f6b5
  ":person_biking:": "icon_person_biking", # v6  \u1f6b4
  ":trophy:": "icon_trophy", # v6  \u1f3c6
  ":first_place:": "icon_first_place", # v9  \u1f947
  ":second_place:": "icon_second_place", # v9  \u1f948
  ":third_place:": "icon_third_place", # v9  \u1f949
  ":medal:": "icon_medal", # v7  \u1f3c5
  ":military_medal:": "icon_military_medal", # v7  \u1f396
  ":rosette:": "icon_rosette", # v7  \u1f3f5
  ":reminder_ribbon:": "icon_reminder_ribbon", # v7  \u1f397
  ":ticket:": "icon_ticket", # v6  \u1f3ab
  ":tickets:": "icon_tickets", # v7  \u1f39f
  ":circus_tent:": "icon_circus_tent", # v6  \u1f3aa
  ":person_juggling:": "icon_person_juggling", # v9  \u1f939
  ":performing_arts:": "icon_performing_arts", # v6  \u1f3ad
  ":clapper:": "icon_clapper", # v6  \u1f3ac
  ":microphone:": "icon_microphone", # v6  \u1f3a4
  ":headphones:": "icon_headphones", # v6  \u1f3a7
  ":musical_score:": "icon_musical_score", # v6  \u1f3bc
  ":musical_keyboard:": "icon_musical_keyboard", # v6  \u1f3b9
  ":drum:": "icon_drum", # v9  \u1f941
  ":saxophone:": "icon_saxophone", # v6  \u1f3b7
  ":trumpet:": "icon_trumpet", # v6  \u1f3ba
  ":guitar:": "icon_guitar", # v6  \u1f3b8
  ":violin:": "icon_violin", # v6  \u1f3bb
  ":game_die:": "icon_game_die", # v6  \u1f3b2
  ":dart:": "icon_dart", # v6  \u1f3af
  ":bowling:": "icon_bowling", # v6  \u1f3b3
  ":video_game:": "icon_video_game", # v6  \u1f3ae
  ":slot_machine:": "icon_slot_machine", # v6  \u1f3b0
  ":iphone:": "icon_iphone", # v6  \u1f4f1
  ":calling:": "icon_calling", # v6  \u1f4f2
  ":computer:": "icon_computer", # v6  \u1f4bb
  ":desktop:": "icon_desktop", # v7  \u1f5a5
  ":printer:": "icon_printer", # v7  \u1f5a8
  ":mouse_three_button:": "icon_mouse_three_button", # v7  \u1f5b1
  ":trackball:": "icon_trackball", # v7  \u1f5b2
  ":joystick:": "icon_joystick", # v7  \u1f579
  ":jigsaw:": "icon_jigsaw", # v11  \u1f9e9
  ":compression:": "icon_compression", # v7  \u1f5dc
  ":minidisc:": "icon_minidisc", # v6  \u1f4bd
  ":floppy_disk:": "icon_floppy_disk", # v6  \u1f4be
  ":camera:": "icon_camera", # v6  \u1f4f7
  ":camera_with_flash:": "icon_camera_with_flash", # v7  \u1f4f8
  ":video_camera:": "icon_video_camera", # v6  \u1f4f9
  ":movie_camera:": "icon_movie_camera", # v6  \u1f3a5
  ":projector:": "icon_projector", # v7  \u1f4fd
  ":film_frames:": "icon_film_frames", # v7  \u1f39e
  ":telephone_receiver:": "icon_telephone_receiver", # v6  \u1f4de
  ":pager:": "icon_pager", # v6  \u1f4df
  ":radio:": "icon_radio", # v6  \u1f4fb
  ":microphone2:": "icon_microphone2", # v7  \u1f399
  ":level_slider:": "icon_level_slider", # v7  \u1f39a
  ":control_knobs:": "icon_control_knobs", # v7  \u1f39b
  ":clock:": "icon_clock", # v7  \u1f570
  ":satellite:": "icon_satellite", # v6  \u1f4e1
  ":compass:": "icon_compass", # v11  \u1f9ed
  ":battery:": "icon_battery", # v6  \u1f50b
  ":electric_plug:": "icon_electric_plug", # v6  \u1f50c
  ":magnet:": "icon_magnet", # v11  \u1f9f2
  ":bulb:": "icon_bulb", # v6  \u1f4a1
  ":flashlight:": "icon_flashlight", # v6  \u1f526
  ":candle:": "icon_candle", # v7  \u1f56f
  ":fire_extinguisher:": "icon_fire_extinguisher", # v11  \u1f9ef
  ":wastebasket:": "icon_wastebasket", # v7  \u1f5d1
  ":money_with_wings:": "icon_money_with_wings", # v6  \u1f4b8
  ":dollar:": "icon_dollar", # v6  \u1f4b5
  ":euro:": "icon_euro", # v6  \u1f4b6
  ":pound:": "icon_pound", # v6  \u1f4b7
  ":moneybag:": "icon_moneybag", # v6  \u1f4b0
  ":credit_card:": "icon_credit_card", # v6  \u1f4b3
  ":nazar_amulet:": "icon_nazar_amulet", # v11  \u1f9ff
  ":bricks:": "icon_bricks", # v11  \u1f9f1
  ":toolbox:": "icon_toolbox", # v11  \u1f9f0
  ":wrench:": "icon_wrench", # v6  \u1f527
  ":hammer:": "icon_hammer", # v6  \u1f528
  ":tools:": "icon_tools", # v7  \u1f6e0
  ":nut_and_bolt:": "icon_nut_and_bolt", # v6  \u1f529
  ":bomb:": "icon_bomb", # v6  \u1f4a3
  ":knife:": "icon_knife", # v6  \u1f52a
  ":dagger:": "icon_dagger", # v7  \u1f5e1
  ":shield:": "icon_shield", # v7  \u1f6e1
  ":smoking:": "icon_smoking", # v6  \u1f6ac
  ":amphora:": "icon_amphora", # v8  \u1f3fa
  ":crystal_ball:": "icon_crystal_ball", # v6  \u1f52e
  ":prayer_beads:": "icon_prayer_beads", # v8  \u1f4ff
  ":barber:": "icon_barber", # v6  \u1f488
  ":test_tube:": "icon_test_tube", # v11  \u1f9ea
  ":petri_dish:": "icon_petri_dish", # v11  \u1f9eb
  ":abacus:": "icon_abacus", # v11  \u1f9ee
  ":telescope:": "icon_telescope", # v6  \u1f52d
  ":microscope:": "icon_microscope", # v6  \u1f52c
  ":hole:": "icon_hole", # v7  \u1f573
  ":pill:": "icon_pill", # v6  \u1f48a
  ":syringe:": "icon_syringe", # v6  \u1f489
  ":thermometer:": "icon_thermometer", # v7  \u1f321
  ":toilet:": "icon_toilet", # v6  \u1f6bd
  ":potable_water:": "icon_potable_water", # v6  \u1f6b0
  ":shower:": "icon_shower", # v6  \u1f6bf
  ":bathtub:": "icon_bathtub", # v6  \u1f6c1
  ":bath:": "icon_bath", # v6  \u1f6c0
  ":broom:": "icon_broom", # v11  \u1f9f9
  ":basket:": "icon_basket", # v11  \u1f9fa
  ":roll_of_paper:": "icon_roll_of_paper", # v11  \u1f9fb
  ":soap:": "icon_soap", # v11  \u1f9fc
  ":sponge:": "icon_sponge", # v11  \u1f9fd
  ":squeeze_bottle:": "icon_squeeze_bottle", # v11  \u1f9f4
  ":thread:": "icon_thread", # v11  \u1f9f5
  ":yarn:": "icon_yarn", # v11  \u1f9f6
  ":bellhop:": "icon_bellhop", # v7  \u1f6ce
  ":key2:": "icon_key2", # v7  \u1f5dd
  ":door:": "icon_door", # v6  \u1f6aa
  ":couch:": "icon_couch", # v7  \u1f6cb
  ":sleeping_accommodation:": "icon_sleeping_accommodation", # v7  \u1f6cc
  ":teddy_bear:": "icon_teddy_bear", # v11  \u1f9f8
  ":frame_photo:": "icon_frame_photo", # v7  \u1f5bc
  ":shopping_bags:": "icon_shopping_bags", # v7  \u1f6cd
  ":shopping_cart:": "icon_shopping_cart", # v9  \u1f6d2
  ":gift:": "icon_gift", # v6  \u1f381
  ":balloon:": "icon_balloon", # v6  \u1f388
  ":flags:": "icon_flags", # v6  \u1f38f
  ":ribbon:": "icon_ribbon", # v6  \u1f380
  ":confetti_ball:": "icon_confetti_ball", # v6  \u1f38a
  ":tada:": "icon_tada", # v6  \u1f389
  ":dolls:": "icon_dolls", # v6  \u1f38e
  ":izakaya_lantern:": "icon_izakaya_lantern", # v6  \u1f3ee
  ":wind_chime:": "icon_wind_chime", # v6  \u1f390
  ":red_envelope:": "icon_red_envelope", # v11  \u1f9e7
  ":envelope_with_arrow:": "icon_envelope_with_arrow", # v6  \u1f4e9
  ":incoming_envelope:": "icon_incoming_envelope", # v6  \u1f4e8
  ":e_mail:": "icon_e_mail", # v6  \u1f4e7
  ":love_letter:": "icon_love_letter", # v6  \u1f48c
  ":inbox_tray:": "icon_inbox_tray", # v6  \u1f4e5
  ":outbox_tray:": "icon_outbox_tray", # v6  \u1f4e4
  ":package:": "icon_package", # v6  \u1f4e6
  ":label:": "icon_label", # v7  \u1f3f7
  ":mailbox_closed:": "icon_mailbox_closed", # v6  \u1f4ea
  ":mailbox:": "icon_mailbox", # v6  \u1f4eb
  ":mailbox_with_mail:": "icon_mailbox_with_mail", # v6  \u1f4ec
  ":mailbox_with_no_mail:": "icon_mailbox_with_no_mail", # v6  \u1f4ed
  ":postbox:": "icon_postbox", # v6  \u1f4ee
  ":postal_horn:": "icon_postal_horn", # v6  \u1f4ef
  ":scroll:": "icon_scroll", # v6  \u1f4dc
  ":page_with_curl:": "icon_page_with_curl", # v6  \u1f4c3
  ":page_facing_up:": "icon_page_facing_up", # v6  \u1f4c4
  ":receipt:": "icon_receipt", # v11  \u1f9fe
  ":bookmark_tabs:": "icon_bookmark_tabs", # v6  \u1f4d1
  ":bar_chart:": "icon_bar_chart", # v6  \u1f4ca
  ":chart_with_upwards_trend:": "icon_chart_with_upwards_trend", # v6  \u1f4c8
  ":chart_with_downwards_trend:": "icon_chart_with_downwards_trend", # v6  \u1f4c9
  ":notepad_spiral:": "icon_notepad_spiral", # v7  \u1f5d2
  ":calendar_spiral:": "icon_calendar_spiral", # v7  \u1f5d3
  ":calendar:": "icon_calendar", # v6  \u1f4c6
  ":date:": "icon_date", # v6  \u1f4c5
  ":card_index:": "icon_card_index", # v6  \u1f4c7
  ":card_box:": "icon_card_box", # v7  \u1f5c3
  ":ballot_box:": "icon_ballot_box", # v7  \u1f5f3
  ":file_cabinet:": "icon_file_cabinet", # v7  \u1f5c4
  ":clipboard:": "icon_clipboard", # v6  \u1f4cb
  ":file_folder:": "icon_file_folder", # v6  \u1f4c1
  ":open_file_folder:": "icon_open_file_folder", # v6  \u1f4c2
  ":dividers:": "icon_dividers", # v7  \u1f5c2
  ":newspaper2:": "icon_newspaper2", # v7  \u1f5de
  ":newspaper:": "icon_newspaper", # v6  \u1f4f0
  ":notebook:": "icon_notebook", # v6  \u1f4d3
  ":notebook_with_decorative_cover:": "icon_notebook_with_decorative_cover", # v6  \u1f4d4
  ":ledger:": "icon_ledger", # v6  \u1f4d2
  ":closed_book:": "icon_closed_book", # v6  \u1f4d5
  ":green_book:": "icon_green_book", # v6  \u1f4d7
  ":blue_book:": "icon_blue_book", # v6  \u1f4d8
  ":orange_book:": "icon_orange_book", # v6  \u1f4d9
  ":books:": "icon_books", # v6  \u1f4da
  ":book:": "icon_book", # v6  \u1f4d6
  ":bookmark:": "icon_bookmark", # v6  \u1f516
  ":link:": "icon_link", # v6  \u1f517
  ":paperclip:": "icon_paperclip", # v6  \u1f4ce
  ":paperclips:": "icon_paperclips", # v7  \u1f587
  ":triangular_ruler:": "icon_triangular_ruler", # v6  \u1f4d0
  ":straight_ruler:": "icon_straight_ruler", # v6  \u1f4cf
  ":safety_pin:": "icon_safety_pin", # v11  \u1f9f7
  ":pushpin:": "icon_pushpin", # v6  \u1f4cc
  ":round_pushpin:": "icon_round_pushpin", # v6  \u1f4cd
  ":pen_ballpoint:": "icon_pen_ballpoint", # v7  \u1f58a
  ":pen_fountain:": "icon_pen_fountain", # v7  \u1f58b
  ":paintbrush:": "icon_paintbrush", # v7  \u1f58c
  ":crayon:": "icon_crayon", # v7  \u1f58d
  ":pencil:": "icon_pencil", # v6  \u1f4dd
  ":mag_right:": "icon_mag_right", # v6  \u1f50e
  ":lock_with_ink_pen:": "icon_lock_with_ink_pen", # v6  \u1f50f
  ":closed_lock_with_key:": "icon_closed_lock_with_key", # v6  \u1f510
  ":mouse:": "icon_mouse", # v6  \u1f42d
  ":hamster:": "icon_hamster", # v6  \u1f439
  ":rabbit:": "icon_rabbit", # v6  \u1f430
  ":raccoon:": "icon_raccoon", # v11  \u1f99d
  ":bear:": "icon_bear", # v6  \u1f43b
  ":panda_face:": "icon_panda_face", # v6  \u1f43c
  ":kangaroo:": "icon_kangaroo", # v11  \u1f998
  ":badger:": "icon_badger", # v11  \u1f9a1
  ":koala:": "icon_koala", # v6  \u1f428
  ":tiger:": "icon_tiger", # v6  \u1f42f
  ":lion_face:": "icon_lion_face", # v8  \u1f981
  ":pig_nose:": "icon_pig_nose", # v6  \u1f43d
  ":frog:": "icon_frog", # v6  \u1f438
  ":monkey_face:": "icon_monkey_face", # v6  \u1f435
  ":see_no_evil:": "icon_see_no_evil", # v6  \u1f648
  ":hear_no_evil:": "icon_hear_no_evil", # v6  \u1f649
  ":speak_no_evil:": "icon_speak_no_evil", # v6  \u1f64a
  ":monkey:": "icon_monkey", # v6  \u1f412
  ":chicken:": "icon_chicken", # v6  \u1f414
  ":penguin:": "icon_penguin", # v6  \u1f427
  ":bird:": "icon_bird", # v6  \u1f426
  ":baby_chick:": "icon_baby_chick", # v6  \u1f424
  ":hatching_chick:": "icon_hatching_chick", # v6  \u1f423
  ":hatched_chick:": "icon_hatched_chick", # v6  \u1f425
  ":duck:": "icon_duck", # v9  \u1f986
  ":swan:": "icon_swan", # v11  \u1f9a2
  ":eagle:": "icon_eagle", # v9  \u1f985
  ":parrot:": "icon_parrot", # v11  \u1f99c
  ":peacock:": "icon_peacock", # v11  \u1f99a
  ":wolf:": "icon_wolf", # v6  \u1f43a
  ":boar:": "icon_boar", # v6  \u1f417
  ":horse:": "icon_horse", # v6  \u1f434
  ":unicorn:": "icon_unicorn", # v8  \u1f984
  ":butterfly:": "icon_butterfly", # v9  \u1f98b
  ":snail:": "icon_snail", # v6  \u1f40c
  ":shell:": "icon_shell", # v6  \u1f41a
  ":beetle:": "icon_beetle", # v6  \u1f41e
  ":cricket:": "icon_cricket", # v10  \u1f997
  ":spider:": "icon_spider", # v7  \u1f577
  ":spider_web:": "icon_spider_web", # v7  \u1f578
  ":scorpion:": "icon_scorpion", # v8  \u1f982
  ":mosquito:": "icon_mosquito", # v11  \u1f99f
  ":microbe:": "icon_microbe", # v11  \u1f9a0
  ":turtle:": "icon_turtle", # v6  \u1f422
  ":snake:": "icon_snake", # v6  \u1f40d
  ":lizard:": "icon_lizard", # v9  \u1f98e
  ":t_rex:": "icon_t_rex", # v10  \u1f996
  ":sauropod:": "icon_sauropod", # v10  \u1f995
  ":octopus:": "icon_octopus", # v6  \u1f419
  ":squid:": "icon_squid", # v9  \u1f991
  ":shrimp:": "icon_shrimp", # v9  \u1f990
  ":crab:": "icon_crab", # v8  \u1f980
  ":lobster:": "icon_lobster", # v11  \u1f99e
  ":blowfish:": "icon_blowfish", # v6  \u1f421
  ":tropical_fish:": "icon_tropical_fish", # v6  \u1f420
  ":fish:": "icon_fish", # v6  \u1f41f
  ":dolphin:": "icon_dolphin", # v6  \u1f42c
  ":whale:": "icon_whale", # v6  \u1f433
  ":whale2:": "icon_whale2", # v6  \u1f40b
  ":shark:": "icon_shark", # v9  \u1f988
  ":crocodile:": "icon_crocodile", # v6  \u1f40a
  ":tiger2:": "icon_tiger2", # v6  \u1f405
  ":leopard:": "icon_leopard", # v6  \u1f406
  ":zebra:": "icon_zebra", # v10  \u1f993
  ":gorilla:": "icon_gorilla", # v9  \u1f98d
  ":elephant:": "icon_elephant", # v6  \u1f418
  ":rhino:": "icon_rhino", # v9  \u1f98f
  ":hippopotamus:": "icon_hippopotamus", # v11  \u1f99b
  ":dromedary_camel:": "icon_dromedary_camel", # v6  \u1f42a
  ":camel:": "icon_camel", # v6  \u1f42b
  ":giraffe:": "icon_giraffe", # v10  \u1f992
  ":llama:": "icon_llama", # v11  \u1f999
  ":water_buffalo:": "icon_water_buffalo", # v6  \u1f403
  ":cow2:": "icon_cow2", # v6  \u1f404
  ":racehorse:": "icon_racehorse", # v6  \u1f40e
  ":pig2:": "icon_pig2", # v6  \u1f416
  ":sheep:": "icon_sheep", # v6  \u1f411
  ":goat:": "icon_goat", # v6  \u1f410
  ":deer:": "icon_deer", # v9  \u1f98c
  ":dog2:": "icon_dog2", # v6  \u1f415
  ":poodle:": "icon_poodle", # v6  \u1f429
  ":cat2:": "icon_cat2", # v6  \u1f408
  ":rooster:": "icon_rooster", # v6  \u1f413
  ":turkey:": "icon_turkey", # v8  \u1f983
  ":dove:": "icon_dove", # v7  \u1f54a
  ":rabbit2:": "icon_rabbit2", # v6  \u1f407
  ":mouse2:": "icon_mouse2", # v6  \u1f401
  ":chipmunk:": "icon_chipmunk", # v7  \u1f43f
  ":hedgehog:": "icon_hedgehog", # v10  \u1f994
  ":feet:": "icon_feet", # v6  \u1f43e
  ":dragon:": "icon_dragon", # v6  \u1f409
  ":dragon_face:": "icon_dragon_face", # v6  \u1f432
  ":cactus:": "icon_cactus", # v6  \u1f335
  ":christmas_tree:": "icon_christmas_tree", # v6  \u1f384
  ":evergreen_tree:": "icon_evergreen_tree", # v6  \u1f332
  ":deciduous_tree:": "icon_deciduous_tree", # v6  \u1f333
  ":palm_tree:": "icon_palm_tree", # v6  \u1f334
  ":seedling:": "icon_seedling", # v6  \u1f331
  ":herb:": "icon_herb", # v6  \u1f33f
  ":four_leaf_clover:": "icon_four_leaf_clover", # v6  \u1f340
  ":bamboo:": "icon_bamboo", # v6  \u1f38d
  ":tanabata_tree:": "icon_tanabata_tree", # v6  \u1f38b
  ":leaves:": "icon_leaves", # v6  \u1f343
  ":fallen_leaf:": "icon_fallen_leaf", # v6  \u1f342
  ":maple_leaf:": "icon_maple_leaf", # v6  \u1f341
  ":mushroom:": "icon_mushroom", # v6  \u1f344
  ":ear_of_rice:": "icon_ear_of_rice", # v6  \u1f33e
  ":bouquet:": "icon_bouquet", # v6  \u1f490
  ":tulip:": "icon_tulip", # v6  \u1f337
  ":rose:": "icon_rose", # v6  \u1f339
  ":wilted_rose:": "icon_wilted_rose", # v9  \u1f940
  ":hibiscus:": "icon_hibiscus", # v6  \u1f33a
  ":cherry_blossom:": "icon_cherry_blossom", # v6  \u1f338
  ":blossom:": "icon_blossom", # v6  \u1f33c
  ":sunflower:": "icon_sunflower", # v6  \u1f33b
  ":sun_with_face:": "icon_sun_with_face", # v6  \u1f31e
  ":full_moon_with_face:": "icon_full_moon_with_face", # v6  \u1f31d
  ":first_quarter_moon_with_face:": "icon_first_quarter_moon_with_face", # v6  \u1f31b
  ":last_quarter_moon_with_face:": "icon_last_quarter_moon_with_face", # v6  \u1f31c
  ":new_moon_with_face:": "icon_new_moon_with_face", # v6  \u1f31a
  ":full_moon:": "icon_full_moon", # v6  \u1f315
  ":waning_gibbous_moon:": "icon_waning_gibbous_moon", # v6  \u1f316
  ":last_quarter_moon:": "icon_last_quarter_moon", # v6  \u1f317
  ":waning_crescent_moon:": "icon_waning_crescent_moon", # v6  \u1f318
  ":new_moon:": "icon_new_moon", # v6  \u1f311
  ":waxing_crescent_moon:": "icon_waxing_crescent_moon", # v6  \u1f312
  ":first_quarter_moon:": "icon_first_quarter_moon", # v6  \u1f313
  ":waxing_gibbous_moon:": "icon_waxing_gibbous_moon", # v6  \u1f314
  ":crescent_moon:": "icon_crescent_moon", # v6  \u1f319
  ":earth_americas:": "icon_earth_americas", # v6  \u1f30e
  ":earth_africa:": "icon_earth_africa", # v6  \u1f30d
  ":earth_asia:": "icon_earth_asia", # v6  \u1f30f
  ":dizzy:": "icon_dizzy", # v6  \u1f4ab
  ":star2:": "icon_star2", # v6  \u1f31f
  ":boom:": "icon_boom", # v6  \u1f4a5
  ":fire:": "icon_fire", # v6  \u1f525
  ":cloud_tornado:": "icon_cloud_tornado", # v7  \u1f32a
  ":rainbow:": "icon_rainbow", # v6  \u1f308
  ":white_sun_small_cloud:": "icon_white_sun_small_cloud", # v7  \u1f324
  ":white_sun_cloud:": "icon_white_sun_cloud", # v7  \u1f325
  ":white_sun_rain_cloud:": "icon_white_sun_rain_cloud", # v7  \u1f326
  ":cloud_rain:": "icon_cloud_rain", # v7  \u1f327
  ":cloud_lightning:": "icon_cloud_lightning", # v7  \u1f329
  ":cloud_snow:": "icon_cloud_snow", # v7  \u1f328
  ":wind_blowing_face:": "icon_wind_blowing_face", # v7  \u1f32c
  ":dash:": "icon_dash", # v6  \u1f4a8
  ":droplet:": "icon_droplet", # v6  \u1f4a7
  ":sweat_drops:": "icon_sweat_drops", # v6  \u1f4a6
  ":ocean:": "icon_ocean", # v6  \u1f30a
  ":green_apple:": "icon_green_apple", # v6  \u1f34f
  ":apple:": "icon_apple", # v6  \u1f34e
  ":pear:": "icon_pear", # v6  \u1f350
  ":tangerine:": "icon_tangerine", # v6  \u1f34a
  ":lemon:": "icon_lemon", # v6  \u1f34b
  ":banana:": "icon_banana", # v6  \u1f34c
  ":watermelon:": "icon_watermelon", # v6  \u1f349
  ":grapes:": "icon_grapes", # v6  \u1f347
  ":strawberry:": "icon_strawberry", # v6  \u1f353
  ":melon:": "icon_melon", # v6  \u1f348
  ":cherries:": "icon_cherries", # v6  \u1f352
  ":peach:": "icon_peach", # v6  \u1f351
  ":mango:": "icon_mango", # v11  \u1f96d
  ":pineapple:": "icon_pineapple", # v6  \u1f34d
  ":coconut:": "icon_coconut", # v10  \u1f965
  ":kiwi:": "icon_kiwi", # v9  \u1f95d
  ":tomato:": "icon_tomato", # v6  \u1f345
  ":eggplant:": "icon_eggplant", # v6  \u1f346
  ":avocado:": "icon_avocado", # v9  \u1f951
  ":broccoli:": "icon_broccoli", # v10  \u1f966
  ":leafy_green:": "icon_leafy_green", # v11  \u1f96c
  ":cucumber:": "icon_cucumber", # v9  \u1f952
  ":hot_pepper:": "icon_hot_pepper", # v7  \u1f336
  ":corn:": "icon_corn", # v6  \u1f33d
  ":carrot:": "icon_carrot", # v9  \u1f955
  ":potato:": "icon_potato", # v9  \u1f954
  ":sweet_potato:": "icon_sweet_potato", # v6  \u1f360
  ":croissant:": "icon_croissant", # v9  \u1f950
  ":bread:": "icon_bread", # v6  \u1f35e
  ":french_bread:": "icon_french_bread", # v9  \u1f956
  ":pretzel:": "icon_pretzel", # v10  \u1f968
  ":bagel:": "icon_bagel", # v11  \u1f96f
  ":cheese:": "icon_cheese", # v8  \u1f9c0
  ":cooking:": "icon_cooking", # v6  \u1f373
  ":pancakes:": "icon_pancakes", # v9  \u1f95e
  ":bacon:": "icon_bacon", # v9  \u1f953
  ":cut_of_meat:": "icon_cut_of_meat", # v10  \u1f969
  ":poultry_leg:": "icon_poultry_leg", # v6  \u1f357
  ":meat_on_bone:": "icon_meat_on_bone", # v6  \u1f356
  ":hotdog:": "icon_hotdog", # v8  \u1f32d
  ":hamburger:": "icon_hamburger", # v6  \u1f354
  ":fries:": "icon_fries", # v6  \u1f35f
  ":pizza:": "icon_pizza", # v6  \u1f355
  ":sandwich:": "icon_sandwich", # v10  \u1f96a
  ":stuffed_flatbread:": "icon_stuffed_flatbread", # v9  \u1f959
  ":taco:": "icon_taco", # v8  \u1f32e
  ":burrito:": "icon_burrito", # v8  \u1f32f
  ":salad:": "icon_salad", # v9  \u1f957
  ":shallow_pan_of_food:": "icon_shallow_pan_of_food", # v9  \u1f958
  ":canned_food:": "icon_canned_food", # v10  \u1f96b
  ":spaghetti:": "icon_spaghetti", # v6  \u1f35d
  ":ramen:": "icon_ramen", # v6  \u1f35c
  ":stew:": "icon_stew", # v6  \u1f372
  ":curry:": "icon_curry", # v6  \u1f35b
  ":sushi:": "icon_sushi", # v6  \u1f363
  ":bento:": "icon_bento", # v6  \u1f371
  ":fried_shrimp:": "icon_fried_shrimp", # v6  \u1f364
  ":rice_ball:": "icon_rice_ball", # v6  \u1f359
  ":rice:": "icon_rice", # v6  \u1f35a
  ":rice_cracker:": "icon_rice_cracker", # v6  \u1f358
  ":fish_cake:": "icon_fish_cake", # v6  \u1f365
  ":fortune_cookie:": "icon_fortune_cookie", # v10  \u1f960
  ":oden:": "icon_oden", # v6  \u1f362
  ":dango:": "icon_dango", # v6  \u1f361
  ":shaved_ice:": "icon_shaved_ice", # v6  \u1f367
  ":ice_cream:": "icon_ice_cream", # v6  \u1f368
  ":icecream:": "icon_icecream", # v6  \u1f366
  ":cake:": "icon_cake", # v6  \u1f370
  ":birthday:": "icon_birthday", # v6  \u1f382
  ":moon_cake:": "icon_moon_cake", # v11  \u1f96e
  ":cupcake:": "icon_cupcake", # v11  \u1f9c1
  ":custard:": "icon_custard", # v6  \u1f36e
  ":lollipop:": "icon_lollipop", # v6  \u1f36d
  ":candy:": "icon_candy", # v6  \u1f36c
  ":chocolate_bar:": "icon_chocolate_bar", # v6  \u1f36b
  ":popcorn:": "icon_popcorn", # v8  \u1f37f
  ":salt:": "icon_salt", # v11  \u1f9c2
  ":doughnut:": "icon_doughnut", # v6  \u1f369
  ":dumpling:": "icon_dumpling", # v10  \u1f95f
  ":cookie:": "icon_cookie", # v6  \u1f36a
  ":chestnut:": "icon_chestnut", # v6  \u1f330
  ":peanuts:": "icon_peanuts", # v9  \u1f95c
  ":honey_pot:": "icon_honey_pot", # v6  \u1f36f
  ":milk:": "icon_milk", # v9  \u1f95b
  ":baby_bottle:": "icon_baby_bottle", # v6  \u1f37c
  ":cup_with_straw:": "icon_cup_with_straw", # v10  \u1f964
  ":sake:": "icon_sake", # v6  \u1f376
  ":beer:": "icon_beer", # v6  \u1f37a
  ":beers:": "icon_beers", # v6  \u1f37b
  ":champagne_glass:": "icon_champagne_glass", # v9  \u1f942
  ":wine_glass:": "icon_wine_glass", # v6  \u1f377
  ":tumbler_glass:": "icon_tumbler_glass", # v9  \u1f943
  ":cocktail:": "icon_cocktail", # v6  \u1f378
  ":tropical_drink:": "icon_tropical_drink", # v6  \u1f379
  ":champagne:": "icon_champagne", # v8  \u1f37e
  ":spoon:": "icon_spoon", # v9  \u1f944
  ":fork_and_knife:": "icon_fork_and_knife", # v6  \u1f374
  ":fork_knife_plate:": "icon_fork_knife_plate", # v7  \u1f37d
  ":bowl_with_spoon:": "icon_bowl_with_spoon", # v10  \u1f963
  ":takeout_box:": "icon_takeout_box", # v10  \u1f961
  ":chopsticks:": "icon_chopsticks", # v10  \u1f962
  ":grinning:": "icon_grinning", # v6.1  \u1f600
  ":smiley:": "icon_smiley", # v6  \u1f603
  ":smile:": "icon_smile", # v6  \u1f604
  ":grin:": "icon_grin", # v6  \u1f601
  ":laughing:": "icon_laughing", # v6  \u1f606
  ":sweat_smile:": "icon_sweat_smile", # v6  \u1f605
  ":rofl:": "icon_rofl", # v9  \u1f923
  ":blush:": "icon_blush", # v6  \u1f60a
  ":innocent:": "icon_innocent", # v6  \u1f607
  ":slight_smile:": "icon_slight_smile", # v7  \u1f642
  ":upside_down:": "icon_upside_down", # v8  \u1f643
  ":wink:": "icon_wink", # v6  \u1f609
  ":relieved:": "icon_relieved", # v6  \u1f60c
  ":heart_eyes:": "icon_heart_eyes", # v6  \u1f60d
  ":kissing_heart:": "icon_kissing_heart", # v6  \u1f618
  ":smiling_face_with_3_hearts:": "icon_smiling_face_with_3_hearts", # v11  \u1f970
  ":kissing:": "icon_kissing", # v6.1  \u1f617
  ":kissing_smiling_eyes:": "icon_kissing_smiling_eyes", # v6.1  \u1f619
  ":kissing_closed_eyes:": "icon_kissing_closed_eyes", # v6  \u1f61a
  ":stuck_out_tongue:": "icon_stuck_out_tongue", # v6.1  \u1f61b
  ":stuck_out_tongue_closed_eyes:": "icon_stuck_out_tongue_closed_eyes", # v6  \u1f61d
  ":stuck_out_tongue_winking_eye:": "icon_stuck_out_tongue_winking_eye", # v6  \u1f61c
  ":zany_face:": "icon_zany_face", # v10  \u1f92a
  ":face_with_raised_eyebrow:": "icon_face_with_raised_eyebrow", # v10  \u1f928
  ":face_with_monocle:": "icon_face_with_monocle", # v10  \u1f9d0
  ":nerd:": "icon_nerd", # v8  \u1f913
  ":sunglasses:": "icon_sunglasses", # v6  \u1f60e
  ":star_struck:": "icon_star_struck", # v10  \u1f929
  ":partying_face:": "icon_partying_face", # v11  \u1f973
  ":smirk:": "icon_smirk", # v6  \u1f60f
  ":unamused:": "icon_unamused", # v6  \u1f612
  ":disappointed:": "icon_disappointed", # v6  \u1f61e
  ":pensive:": "icon_pensive", # v6  \u1f614
  ":worried:": "icon_worried", # v6.1  \u1f61f
  ":confused:": "icon_confused", # v6.1  \u1f615
  ":slight_frown:": "icon_slight_frown", # v7  \u1f641
  ":persevere:": "icon_persevere", # v6  \u1f623
  ":confounded:": "icon_confounded", # v6  \u1f616
  ":tired_face:": "icon_tired_face", # v6  \u1f62b
  ":weary:": "icon_weary", # v6  \u1f629
  ":triumph:": "icon_triumph", # v6  \u1f624
  ":angry:": "icon_angry", # v6  \u1f620
  ":rage:": "icon_rage", # v6  \u1f621
  ":face_with_symbols_over_mouth:": "icon_face_with_symbols_over_mouth", # v10  \u1f92c
  ":exploding_head:": "icon_exploding_head", # v10  \u1f92f
  ":flushed:": "icon_flushed", # v6  \u1f633
  ":scream:": "icon_scream", # v6  \u1f631
  ":fearful:": "icon_fearful", # v6  \u1f628
  ":cold_sweat:": "icon_cold_sweat", # v6  \u1f630
  ":hot_face:": "icon_hot_face", # v11  \u1f975
  ":cold_face:": "icon_cold_face", # v11  \u1f976
  ":pleading_face:": "icon_pleading_face", # v11  \u1f97a
  ":disappointed_relieved:": "icon_disappointed_relieved", # v6  \u1f625
  ":sweat:": "icon_sweat", # v6  \u1f613
  ":hugging:": "icon_hugging", # v8  \u1f917
  ":thinking:": "icon_thinking", # v8  \u1f914
  ":face_with_hand_over_mouth:": "icon_face_with_hand_over_mouth", # v10  \u1f92d
  ":shushing_face:": "icon_shushing_face", # v10  \u1f92b
  ":lying_face:": "icon_lying_face", # v9  \u1f925
  ":no_mouth:": "icon_no_mouth", # v6  \u1f636
  ":neutral_face:": "icon_neutral_face", # v6  \u1f610
  ":expressionless:": "icon_expressionless", # v6.1  \u1f611
  ":grimacing:": "icon_grimacing", # v6.1  \u1f62c
  ":rolling_eyes:": "icon_rolling_eyes", # v8  \u1f644
  ":hushed:": "icon_hushed", # v6.1  \u1f62f
  ":frowning:": "icon_frowning", # v6.1  \u1f626
  ":anguished:": "icon_anguished", # v6.1  \u1f627
  ":open_mouth:": "icon_open_mouth", # v6.1  \u1f62e
  ":astonished:": "icon_astonished", # v6  \u1f632
  ":sleeping:": "icon_sleeping", # v6.1  \u1f634
  ":drooling_face:": "icon_drooling_face", # v9  \u1f924
  ":sleepy:": "icon_sleepy", # v6  \u1f62a
  ":dizzy_face:": "icon_dizzy_face", # v6  \u1f635
  ":zipper_mouth:": "icon_zipper_mouth", # v8  \u1f910
  ":woozy_face:": "icon_woozy_face", # v11  \u1f974
  ":nauseated_face:": "icon_nauseated_face", # v9  \u1f922
  ":face_vomiting:": "icon_face_vomiting", # v10  \u1f92e
  ":sneezing_face:": "icon_sneezing_face", # v9  \u1f927
  ":mask:": "icon_mask", # v6  \u1f637
  ":thermometer_face:": "icon_thermometer_face", # v8  \u1f912
  ":head_bandage:": "icon_head_bandage", # v8  \u1f915
  ":money_mouth:": "icon_money_mouth", # v8  \u1f911
  ":cowboy:": "icon_cowboy", # v9  \u1f920
  ":smiling_imp:": "icon_smiling_imp", # v6  \u1f608
  ":japanese_ogre:": "icon_japanese_ogre", # v6  \u1f479
  ":japanese_goblin:": "icon_japanese_goblin", # v6  \u1f47a
  ":clown:": "icon_clown", # v9  \u1f921
  ":poop:": "icon_poop", # v6  \u1f4a9
  ":ghost:": "icon_ghost", # v6  \u1f47b
  ":skull:": "icon_skull", # v6  \u1f480
  ":alien:": "icon_alien", # v6  \u1f47d
  ":space_invader:": "icon_space_invader", # v6  \u1f47e
  ":robot:": "icon_robot", # v8  \u1f916
  ":jack_o_lantern:": "icon_jack_o_lantern", # v6  \u1f383
  ":smiley_cat:": "icon_smiley_cat", # v6  \u1f63a
  ":smile_cat:": "icon_smile_cat", # v6  \u1f638
  ":joy_cat:": "icon_joy_cat", # v6  \u1f639
  ":heart_eyes_cat:": "icon_heart_eyes_cat", # v6  \u1f63b
  ":smirk_cat:": "icon_smirk_cat", # v6  \u1f63c
  ":kissing_cat:": "icon_kissing_cat", # v6  \u1f63d
  ":scream_cat:": "icon_scream_cat", # v6  \u1f640
  ":crying_cat_face:": "icon_crying_cat_face", # v6  \u1f63f
  ":pouting_cat:": "icon_pouting_cat", # v6  \u1f63e
  ":palms_up_together:": "icon_palms_up_together", # v10  \u1f932
  ":open_hands:": "icon_open_hands", # v6  \u1f450
  ":raised_hands:": "icon_raised_hands", # v6  \u1f64c
  ":clap:": "icon_clap", # v6  \u1f44f
  ":handshake:": "icon_handshake", # v9  \u1f91d
  ":thumbsup:": "icon_thumbsup", # v6  \u1f44d
  ":thumbsdown:": "icon_thumbsdown", # v6  \u1f44e
  ":punch:": "icon_punch", # v6  \u1f44a
  ":left_facing_fist:": "icon_left_facing_fist", # v9  \u1f91b
  ":right_facing_fist:": "icon_right_facing_fist", # v9  \u1f91c
  ":fingers_crossed:": "icon_fingers_crossed", # v9  \u1f91e
  ":love_you_gesture:": "icon_love_you_gesture", # v10  \u1f91f
  ":metal:": "icon_metal", # v8  \u1f918
  ":ok_hand:": "icon_ok_hand", # v6  \u1f44c
  ":point_left:": "icon_point_left", # v6  \u1f448
  ":point_right:": "icon_point_right", # v6  \u1f449
  ":point_up_2:": "icon_point_up_2", # v6  \u1f446
  ":point_down:": "icon_point_down", # v6  \u1f447
  ":raised_back_of_hand:": "icon_raised_back_of_hand", # v9  \u1f91a
  ":hand_splayed:": "icon_hand_splayed", # v7  \u1f590
  ":vulcan:": "icon_vulcan", # v7  \u1f596
  ":wave:": "icon_wave", # v6  \u1f44b
  ":call_me:": "icon_call_me", # v9  \u1f919
  ":muscle:": "icon_muscle", # v6  \u1f4aa
  ":foot:": "icon_foot", # v11  \u1f9b6
  ":middle_finger:": "icon_middle_finger", # v7  \u1f595
  ":pray:": "icon_pray", # v6  \u1f64f
  ":ring:": "icon_ring", # v6  \u1f48d
  ":lipstick:": "icon_lipstick", # v6  \u1f484
  ":kiss:": "icon_kiss", # v6  \u1f48b
  ":lips:": "icon_lips", # v6  \u1f444
  ":tongue:": "icon_tongue", # v6  \u1f445
  ":nose:": "icon_nose", # v6  \u1f443
  ":footprints:": "icon_footprints", # v6  \u1f463
  ":eyes:": "icon_eyes", # v6  \u1f440
  ":brain:": "icon_brain", # v10  \u1f9e0
  ":bone:": "icon_bone", # v11  \u1f9b4
  ":tooth:": "icon_tooth", # v11  \u1f9b7
  ":speaking_head:": "icon_speaking_head", # v7  \u1f5e3
  ":bust_in_silhouette:": "icon_bust_in_silhouette", # v6  \u1f464
  ":busts_in_silhouette:": "icon_busts_in_silhouette", # v6  \u1f465
  ":baby:": "icon_baby", # v6  \u1f476
  ":girl:": "icon_girl", # v6  \u1f467
  ":child:": "icon_child", # v10  \u1f9d2
  ":woman:": "icon_woman", # v6  \u1f469
  ":adult:": "icon_adult", # v10  \u1f9d1
  ":blond_haired_person:": "icon_blond_haired_person", # v6  \u1f471
  ":bearded_person:": "icon_bearded_person", # v10  \u1f9d4
  ":older_woman:": "icon_older_woman", # v6  \u1f475
  ":older_adult:": "icon_older_adult", # v10  \u1f9d3
  ":older_man:": "icon_older_man", # v6  \u1f474
  ":man_with_chinese_cap:": "icon_man_with_chinese_cap", # v6  \u1f472
  ":person_wearing_turban:": "icon_person_wearing_turban", # v6  \u1f473
  ":woman_with_headscarf:": "icon_woman_with_headscarf", # v10  \u1f9d5
  ":police_officer:": "icon_police_officer", # v6  \u1f46e
  ":construction_worker:": "icon_construction_worker", # v6  \u1f477
  ":guard:": "icon_guard", # v6  \u1f482
  ":detective:": "icon_detective", # v7  \u1f575
  ":bride_with_veil:": "icon_bride_with_veil", # v6  \u1f470
  ":man_in_tuxedo:": "icon_man_in_tuxedo", # v9  \u1f935
  ":princess:": "icon_princess", # v6  \u1f478
  ":prince:": "icon_prince", # v9  \u1f934
  ":mrs_claus:": "icon_mrs_claus", # v9  \u1f936
  ":santa:": "icon_santa", # v6  \u1f385
  ":superhero:": "icon_superhero", # v11  \u1f9b8
  ":supervillain:": "icon_supervillain", # v11  \u1f9b9
  ":mage:": "icon_mage", # v10  \u1f9d9
  ":vampire:": "icon_vampire", # v10  \u1f9db
  ":zombie:": "icon_zombie", # v10  \u1f9df
  ":genie:": "icon_genie", # v10  \u1f9de
  ":merperson:": "icon_merperson", # v10  \u1f9dc
  ":fairy:": "icon_fairy", # v10  \u1f9da
  ":angel:": "icon_angel", # v6  \u1f47c
  ":pregnant_woman:": "icon_pregnant_woman", # v9  \u1f930
  ":breast_feeding:": "icon_breast_feeding", # v10  \u1f931
  ":person_bowing:": "icon_person_bowing", # v6  \u1f647
  ":person_tipping_hand:": "icon_person_tipping_hand", # v6  \u1f481
  ":person_gesturing_no:": "icon_person_gesturing_no", # v6  \u1f645
  ":person_gesturing_ok:": "icon_person_gesturing_ok", # v6  \u1f646
  ":person_raising_hand:": "icon_person_raising_hand", # v6  \u1f64b
  ":person_facepalming:": "icon_person_facepalming", # v9  \u1f926
  ":person_shrugging:": "icon_person_shrugging", # v9  \u1f937
  ":person_pouting:": "icon_person_pouting", # v6  \u1f64e
  ":person_frowning:": "icon_person_frowning", # v6  \u1f64d
  ":person_getting_haircut:": "icon_person_getting_haircut", # v6  \u1f487
  ":person_getting_massage:": "icon_person_getting_massage", # v6  \u1f486
  ":person_in_steamy_room:": "icon_person_in_steamy_room", # v10  \u1f9d6
  ":nail_care:": "icon_nail_care", # v6  \u1f485
  ":selfie:": "icon_selfie", # v9  \u1f933
  ":dancer:": "icon_dancer", # v6  \u1f483
  ":man_dancing:": "icon_man_dancing", # v9  \u1f57a
  ":people_with_bunny_ears_partying:": "icon_people_with_bunny_ears_partying", # v6  \u1f46f
  ":levitate:": "icon_levitate", # v7  \u1f574
  ":person_walking:": "icon_person_walking", # v6  \u1f6b6
  ":person_running:": "icon_person_running", # v6  \u1f3c3
  ":couple:": "icon_couple", # v6  \u1f46b
  ":two_women_holding_hands:": "icon_two_women_holding_hands", # v6  \u1f46d
  ":two_men_holding_hands:": "icon_two_men_holding_hands", # v6  \u1f46c
  ":couple_with_heart:": "icon_couple_with_heart", # v6  \u1f491
  ":couplekiss:": "icon_couplekiss", # v6  \u1f48f
  ":family:": "icon_family", # v6  \u1f46a
  ":coat:": "icon_coat", # v10  \u1f9e5
  ":womans_clothes:": "icon_womans_clothes", # v6  \u1f45a
  ":shirt:": "icon_shirt", # v6  \u1f455
  ":jeans:": "icon_jeans", # v6  \u1f456
  ":necktie:": "icon_necktie", # v6  \u1f454
  ":dress:": "icon_dress", # v6  \u1f457
  ":bikini:": "icon_bikini", # v6  \u1f459
  ":kimono:": "icon_kimono", # v6  \u1f458
  ":lab_coat:": "icon_lab_coat", # v11  \u1f97c
  ":high_heel:": "icon_high_heel", # v6  \u1f460
  ":sandal:": "icon_sandal", # v6  \u1f461
  ":boot:": "icon_boot", # v6  \u1f462
  ":mans_shoe:": "icon_mans_shoe", # v6  \u1f45e
  ":athletic_shoe:": "icon_athletic_shoe", # v6  \u1f45f
  ":hiking_boot:": "icon_hiking_boot", # v11  \u1f97e
  ":womans_flat_shoe:": "icon_womans_flat_shoe", # v11  \u1f97f
  ":socks:": "icon_socks", # v10  \u1f9e6
  ":gloves:": "icon_gloves", # v10  \u1f9e4
  ":scarf:": "icon_scarf", # v10  \u1f9e3
  ":tophat:": "icon_tophat", # v6  \u1f3a9
  ":billed_cap:": "icon_billed_cap", # v10  \u1f9e2
  ":womans_hat:": "icon_womans_hat", # v6  \u1f452
  ":mortar_board:": "icon_mortar_board", # v6  \u1f393
  ":crown:": "icon_crown", # v6  \u1f451
  ":pouch:": "icon_pouch", # v6  \u1f45d
  ":purse:": "icon_purse", # v6  \u1f45b
  ":handbag:": "icon_handbag", # v6  \u1f45c
  ":briefcase:": "icon_briefcase", # v6  \u1f4bc
  ":school_satchel:": "icon_school_satchel", # v6  \u1f392
  ":eyeglasses:": "icon_eyeglasses", # v6  \u1f453
  ":dark_sunglasses:": "icon_dark_sunglasses", # v7  \u1f576
  ":goggles:": "icon_goggles", # v11  \u1f97d
  ":closed_umbrella:": "icon_closed_umbrella", # v6  \u1f302
  ":red_haired:": "icon_red_haired", # v11  \u1f9b0
  ":curly_haired:": "icon_curly_haired", # v11  \u1f9b1
  ":white_haired:": "icon_white_haired", # v11  \u1f9b3
  ":bald:": "icon_bald", # v11  \u1f9b2
  ":regional_indicator_z:": "icon_regional_indicator_z", # v6  \u1f1ff
  ":regional_indicator_y:": "icon_regional_indicator_y", # v6  \u1f1fe
  ":regional_indicator_x:": "icon_regional_indicator_x", # v6  \u1f1fd
  ":regional_indicator_w:": "icon_regional_indicator_w", # v6  \u1f1fc
  ":regional_indicator_v:": "icon_regional_indicator_v", # v6  \u1f1fb
  ":regional_indicator_u:": "icon_regional_indicator_u", # v6  \u1f1fa
  ":regional_indicator_t:": "icon_regional_indicator_t", # v6  \u1f1f9
  ":regional_indicator_s:": "icon_regional_indicator_s", # v6  \u1f1f8
  ":regional_indicator_r:": "icon_regional_indicator_r", # v6  \u1f1f7
  ":regional_indicator_q:": "icon_regional_indicator_q", # v6  \u1f1f6
  ":regional_indicator_p:": "icon_regional_indicator_p", # v6  \u1f1f5
  ":regional_indicator_o:": "icon_regional_indicator_o", # v6  \u1f1f4
  ":regional_indicator_n:": "icon_regional_indicator_n", # v6  \u1f1f3
  ":regional_indicator_m:": "icon_regional_indicator_m", # v6  \u1f1f2
  ":regional_indicator_l:": "icon_regional_indicator_l", # v6  \u1f1f1
  ":regional_indicator_k:": "icon_regional_indicator_k", # v6  \u1f1f0
  ":regional_indicator_j:": "icon_regional_indicator_j", # v6  \u1f1ef
  ":regional_indicator_i:": "icon_regional_indicator_i", # v6  \u1f1ee
  ":regional_indicator_h:": "icon_regional_indicator_h", # v6  \u1f1ed
  ":regional_indicator_g:": "icon_regional_indicator_g", # v6  \u1f1ec
  ":regional_indicator_f:": "icon_regional_indicator_f", # v6  \u1f1eb
  ":regional_indicator_e:": "icon_regional_indicator_e", # v6  \u1f1ea
  ":regional_indicator_d:": "icon_regional_indicator_d", # v6  \u1f1e9
  ":regional_indicator_c:": "icon_regional_indicator_c", # v6  \u1f1e8
  ":regional_indicator_b:": "icon_regional_indicator_b", # v6  \u1f1e7
  ":regional_indicator_a:": "icon_regional_indicator_a", # v6  \u1f1e6
  ":red_car:": "icon_red_car", # v6  \u1f697
  ":taxi:": "icon_taxi", # v6  \u1f695
  ":blue_car:": "icon_blue_car", # v6  \u1f699
  ":trolleybus:": "icon_trolleybus", # v6  \u1f68e
  ":race_car:": "icon_race_car", # v7  \u1f3ce
  ":police_car:": "icon_police_car", # v6  \u1f693
  ":ambulance:": "icon_ambulance", # v6  \u1f691
  ":fire_engine:": "icon_fire_engine", # v6  \u1f692
  ":minibus:": "icon_minibus", # v6  \u1f690
  ":truck:": "icon_truck", # v6  \u1f69a
  ":articulated_lorry:": "icon_articulated_lorry", # v6  \u1f69b
  ":tractor:": "icon_tractor", # v6  \u1f69c
  ":scooter:": "icon_scooter", # v9  \u1f6f4
  ":bike:": "icon_bike", # v6  \u1f6b2
  ":motor_scooter:": "icon_motor_scooter", # v9  \u1f6f5
  ":motorcycle:": "icon_motorcycle", # v7  \u1f3cd
  ":rotating_light:": "icon_rotating_light", # v6  \u1f6a8
  ":oncoming_police_car:": "icon_oncoming_police_car", # v6  \u1f694
  ":oncoming_bus:": "icon_oncoming_bus", # v6  \u1f68d
  ":oncoming_automobile:": "icon_oncoming_automobile", # v6  \u1f698
  ":oncoming_taxi:": "icon_oncoming_taxi", # v6  \u1f696
  ":aerial_tramway:": "icon_aerial_tramway", # v6  \u1f6a1
  ":mountain_cableway:": "icon_mountain_cableway", # v6  \u1f6a0
  ":suspension_railway:": "icon_suspension_railway", # v6  \u1f69f
  ":railway_car:": "icon_railway_car", # v6  \u1f683
  ":train:": "icon_train", # v6  \u1f68b
  ":mountain_railway:": "icon_mountain_railway", # v6  \u1f69e
  ":monorail:": "icon_monorail", # v6  \u1f69d
  ":bullettrain_side:": "icon_bullettrain_side", # v6  \u1f684
  ":bullettrain_front:": "icon_bullettrain_front", # v6  \u1f685
  ":light_rail:": "icon_light_rail", # v6  \u1f688
  ":steam_locomotive:": "icon_steam_locomotive", # v6  \u1f682
  ":train2:": "icon_train2", # v6  \u1f686
  ":metro:": "icon_metro", # v6  \u1f687
  ":tram:": "icon_tram", # v6  \u1f68a
  ":station:": "icon_station", # v6  \u1f689
  ":airplane_departure:": "icon_airplane_departure", # v7  \u1f6eb
  ":airplane_arriving:": "icon_airplane_arriving", # v7  \u1f6ec
  ":airplane_small:": "icon_airplane_small", # v7  \u1f6e9
  ":seat:": "icon_seat", # v6  \u1f4ba
  ":luggage:": "icon_luggage", # v11  \u1f9f3
  ":satellite_orbital:": "icon_satellite_orbital", # v7  \u1f6f0
  ":rocket:": "icon_rocket", # v6  \u1f680
  ":flying_saucer:": "icon_flying_saucer", # v10  \u1f6f8
  ":helicopter:": "icon_helicopter", # v6  \u1f681
  ":canoe:": "icon_canoe", # v9  \u1f6f6
  ":speedboat:": "icon_speedboat", # v6  \u1f6a4
  ":motorboat:": "icon_motorboat", # v7  \u1f6e5
  ":cruise_ship:": "icon_cruise_ship", # v7  \u1f6f3
  ":ship:": "icon_ship", # v6  \u1f6a2
  ":construction:": "icon_construction", # v6  \u1f6a7
  ":vertical_traffic_light:": "icon_vertical_traffic_light", # v6  \u1f6a6
  ":traffic_light:": "icon_traffic_light", # v6  \u1f6a5
  ":busstop:": "icon_busstop", # v6  \u1f68f
  ":moyai:": "icon_moyai", # v6  \u1f5ff
  ":statue_of_liberty:": "icon_statue_of_liberty", # v6  \u1f5fd
  ":tokyo_tower:": "icon_tokyo_tower", # v6  \u1f5fc
  ":european_castle:": "icon_european_castle", # v6  \u1f3f0
  ":japanese_castle:": "icon_japanese_castle", # v6  \u1f3ef
  ":stadium:": "icon_stadium", # v7  \u1f3df
  ":ferris_wheel:": "icon_ferris_wheel", # v6  \u1f3a1
  ":roller_coaster:": "icon_roller_coaster", # v6  \u1f3a2
  ":carousel_horse:": "icon_carousel_horse", # v6  \u1f3a0
  ":beach:": "icon_beach", # v7  \u1f3d6
  ":island:": "icon_island", # v7  \u1f3dd
  ":desert:": "icon_desert", # v7  \u1f3dc
  ":volcano:": "icon_volcano", # v6  \u1f30b
  ":mountain_snow:": "icon_mountain_snow", # v7  \u1f3d4
  ":mount_fuji:": "icon_mount_fuji", # v6  \u1f5fb
  ":camping:": "icon_camping", # v7  \u1f3d5
  ":house:": "icon_house", # v6  \u1f3e0
  ":house_with_garden:": "icon_house_with_garden", # v6  \u1f3e1
  ":homes:": "icon_homes", # v7  \u1f3d8
  ":house_abandoned:": "icon_house_abandoned", # v7  \u1f3da
  ":construction_site:": "icon_construction_site", # v7  \u1f3d7
  ":factory:": "icon_factory", # v6  \u1f3ed
  ":office:": "icon_office", # v6  \u1f3e2
  ":department_store:": "icon_department_store", # v6  \u1f3ec
  ":post_office:": "icon_post_office", # v6  \u1f3e3
  ":european_post_office:": "icon_european_post_office", # v6  \u1f3e4
  ":hospital:": "icon_hospital", # v6  \u1f3e5
  ":bank:": "icon_bank", # v6  \u1f3e6
  ":hotel:": "icon_hotel", # v6  \u1f3e8
  ":convenience_store:": "icon_convenience_store", # v6  \u1f3ea
  ":school:": "icon_school", # v6  \u1f3eb
  ":love_hotel:": "icon_love_hotel", # v6  \u1f3e9
  ":wedding:": "icon_wedding", # v6  \u1f492
  ":classical_building:": "icon_classical_building", # v7  \u1f3db
  ":mosque:": "icon_mosque", # v8  \u1f54c
  ":synagogue:": "icon_synagogue", # v8  \u1f54d
  ":kaaba:": "icon_kaaba", # v8  \u1f54b
  ":railway_track:": "icon_railway_track", # v7  \u1f6e4
  ":motorway:": "icon_motorway", # v7  \u1f6e3
  ":japan:": "icon_japan", # v6  \u1f5fe
  ":rice_scene:": "icon_rice_scene", # v6  \u1f391
  ":park:": "icon_park", # v7  \u1f3de
  ":sunrise:": "icon_sunrise", # v6  \u1f305
  ":sunrise_over_mountains:": "icon_sunrise_over_mountains", # v6  \u1f304
  ":stars:": "icon_stars", # v6  \u1f320
  ":sparkler:": "icon_sparkler", # v6  \u1f387
  ":fireworks:": "icon_fireworks", # v6  \u1f386
  ":firecracker:": "icon_firecracker", # v11  \u1f9e8
  ":city_sunset:": "icon_city_sunset", # v6  \u1f307
  ":city_dusk:": "icon_city_dusk", # v6  \u1f306
  ":cityscape:": "icon_cityscape", # v7  \u1f3d9
  ":night_with_stars:": "icon_night_with_stars", # v6  \u1f303
  ":milky_way:": "icon_milky_way", # v6  \u1f30c
  ":bridge_at_night:": "icon_bridge_at_night", # v6  \u1f309
  ":lock:": "icon_lock", # v6  \u1f512
  ":unlock:": "icon_unlock", # v6  \u1f513
  ":foggy:": "icon_foggy", # v6  \u1f301
  ":flag_white:": "icon_flag_white", # v7  \u1f3f3
  ":flag_black:": "icon_flag_black", # v7  \u1f3f4
  ":checkered_flag:": "icon_checkered_flag", # v6  \u1f3c1
  ":triangular_flag_on_post:": "icon_triangular_flag_on_post", # v6  \u1f6a9
  ":crossed_flags:": "icon_crossed_flags"  # v6  \u1f38c
} ## Unicode Standard Emoji http://unicode.org/emoji/charts/full-emoji-list.html
